import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import type { HarnessRegistry } from '@prism/core'

import { createHarnessRegistry } from '@prism/core'

import { createZcodeAdapter } from '../src/adapters/zcode.js'
import { createTeamRegistry } from '../src/registry.js'
import { parseRoleMarkdown } from '../src/role/parse.js'
import { parseTeamMarkdown } from '../src/team/parse.js'

const ROLE_RAW = [
  '---',
  'name: "security-auditor"',
  'description: "白盒安全审计角色。适用于：代码变更的漏洞审计、安全红线核查。不适用于：性能优化。"',
  'color: red',
  'skills:',
  '  - taint_trace',
  'knowledge:',
  '  layers: [global, role]',
  '  books: [security-redline]',
  '---',
  '',
  '# 安全审计师',
  '',
  '## 核心第一原则',
  '**存疑即阻断：漏报可以补，误放不可逆。**',
].join('\n')

const TEAM_RAW = [
  '---',
  'team_id: core-dev',
  'name: 核心研发团队',
  'description: 负责设计、开发、测试与质量收口。',
  'default: false',
  'members:',
  '  - role: dev-1',
  '    count: 2',
  'skills: []',
  'knowledge:',
  '  layers: [global, project]',
  'deposit:',
  '  enabled: true',
  '  default_layer: project',
  '  default_type: pitfall',
  '  priority: medium',
  '  require_note: true',
  'arbitration: [safety, quality]',
  'rework_limit: 2',
  '---',
  '',
  '正文',
].join('\n')

describe('ZCode 适配器（HarnessAdapter 实现）', () => {
  let zcodeDir = ''
  let repoDir = ''

  beforeEach(() => {
    zcodeDir = join(tmpdir(), `prism-zcode-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    repoDir = join(tmpdir(), `prism-repo-${Date.now()}-${Math.random().toString(36).slice(2)}`)
  })
  afterEach(() => {
    /* 临时目录留给系统清理 */
  })

  it('约定字段（harness §4.1）：子路径由 zcodeDir 参数推导，不硬编码', () => {
    const adapter = createZcodeAdapter({ zcodeDir, repoDir })
    expect(adapter.id).toBe('zcode')
    expect(adapter.displayName).toBe('ZCode')
    expect(adapter.agent.globalDir).toBe(join(zcodeDir, 'agents'))
    expect(adapter.agent.teamDir).toBe(join(zcodeDir, 'teams'))
    expect(adapter.agent.filePattern).toBe('<role>.md')
    expect(adapter.agent.frontmatterFields).toEqual(['name', 'description', 'color', 'model', 'thoughtLevel', 'injectAgentsMd'])
    expect(adapter.agent.bodyConvention).toBe('## 核心契约')
    expect(adapter.agent.activation).toBe('session-start')
    expect(adapter.agent.nameMustMatchFile).toBe(true)
    expect(adapter.skill.nativeDir).toBe(join(zcodeDir, 'skills'))
    expect(adapter.model.overridePath).toBe(join(zcodeDir, 'v2', 'agents-state.json'))
    expect(adapter.dispatch?.mechanism).toContain('subagent_type')
    expect(adapter.instructions.file).toBe('AGENTS.md')
    expect(adapter.instructions.projectFile).toBe(join(repoDir, 'AGENTS.md'))
    // 不同 zcodeDir → 不同落点（装配目标由参数决定）
    const other = createZcodeAdapter({ zcodeDir: join(tmpdir(), 'another-zcode') })
    expect(other.skill.nativeDir).toBe(join(tmpdir(), 'another-zcode', 'skills'))
    expect(other.agent.projectDir).toBe('<repo>/.zcode/agents')
  })

  it('detect：目录存在/不存在（只读探测）', async () => {
    const adapter = createZcodeAdapter({ zcodeDir })
    const absent = await adapter.detect()
    expect(absent).toEqual({ installed: false, reason: expect.stringContaining(zcodeDir) })
    const { mkdirSync } = await import('node:fs')
    mkdirSync(zcodeDir, { recursive: true })
    const present = await adapter.detect()
    expect(present).toEqual({ installed: true, configDir: zcodeDir })
  })

  it('renderRole：产物落在 <globalDir>/<name>.md；可被 parseRole 还原（写读对称）', () => {
    const adapter = createZcodeAdapter({ zcodeDir })
    const role = parseRoleMarkdown(ROLE_RAW)
    const file = adapter.renderRole(role)
    expect(file.path).toBe(join(zcodeDir, 'agents', 'security-auditor.md'))
    expect(file.format).toBe('markdown')
    expect(file.writePolicy).toBe('overwrite')
    expect(file.marker).toBe('<!-- generated by prism (role: security-auditor) -->')
    expect(file.content.trimEnd().endsWith(file.marker)).toBe(true)
    // ZCode 约束：name 与文件名一致（nameMustMatchFile）
    const filename = file.path.replaceAll('\\', '/').split('/').pop() ?? ''
    expect(filename.replace(/\.md$/, '')).toBe(role.name)
    const back = adapter.parseRole(file.content, filename)
    expect(back.name).toBe(role.name)
    expect(back.principle).toBe(role.principle)
    expect(back.skills).toEqual(['taint_trace'])
    expect(back.knowledge).toEqual({ layers: ['global', 'role'], books: ['security-redline'] })
  })

  it('渲染 frontmatter 引号约束：含冒号的值加引号（harness §2.1，find-skills 实坑）', () => {
    const adapter = createZcodeAdapter({ zcodeDir })
    const role = parseRoleMarkdown(ROLE_RAW)
    const content = adapter.renderRole(role).content
    const fmBlock = content.slice(content.indexOf('---\n') + 4, content.indexOf('\n---', 4))
    const descLine = fmBlock.split('\n').find((l) => l.startsWith('description:'))
    expect(descLine).toMatch(/^description: ".*"$/) // 含中文冒号/全角标点 → 双引号包裹
    expect(content).not.toMatch(/^skills:/m) // Prism 扩展不进 frontmatter（只在正文/省略）
    expect(content).not.toMatch(/^knowledge:/m)
  })

  it('renderTeamInstructions：有 repoDir → merge 标记块；无 repoDir → null', () => {
    const team = parseTeamMarkdown(TEAM_RAW)
    const withRepo = createZcodeAdapter({ zcodeDir, repoDir })
    const file = withRepo.renderTeamInstructions(team)
    expect(file?.writePolicy).toBe('merge')
    expect(file?.path).toBe(join(repoDir, 'AGENTS.md'))
    expect(file?.content).toContain('<!-- prism:team:core-dev:start -->')
    expect(file?.content).toContain('safety > quality')
    expect(createZcodeAdapter({ zcodeDir }).renderTeamInstructions(team)).toBeNull()
  })
})

describe('HarnessRegistry（core 下沉：编译期注册，运行期单激活）', () => {
  it('register / activate / active / list', async () => {
    const registry: HarnessRegistry = createHarnessRegistry()
    const zcode = createZcodeAdapter({ zcodeDir: join(tmpdir(), 'reg-zcode') })
    registry.register(zcode)
    expect(registry.list().map((a) => a.id)).toEqual(['zcode'])
    const activated = registry.activate('zcode')
    expect(activated.id).toBe('zcode')
    expect(registry.active()).toBe(activated)
    expect(() => registry.activate('claude-code')).toThrow(/not registered/)
    expect(() => createHarnessRegistry().active()).toThrow(/no harness adapter activated/)
    // 接口下沉核验：skills 包（dev-2）只依赖 @prism/core 即可取到 skill.nativeDir
    expect(existsSync(zcode.skill.nativeDir ?? '/')).toBe(false) // 仅是路径声明，不要求存在
  })
})

describe('团队注册表（TeamRegistry）', () => {
  it('loadFromDir 载入 <team_id>.md；坏文件计入 failures 不中断', async () => {
    const { mkdirSync, writeFileSync } = await import('node:fs')
    const dir = join(tmpdir(), `prism-teams-${Date.now()}`)
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'core-dev.md'), TEAM_RAW)
    writeFileSync(join(dir, 'broken.md'), '---\nteam_id: &a x\n---\n')
    const registry = createTeamRegistry()
    const { teams, failures } = await registry.loadFromDirDetailed(dir)
    expect(teams.map((t) => t.team_id)).toEqual(['core-dev'])
    expect(registry.get('core-dev')?.name).toBe('核心研发团队')
    expect(failures).toHaveLength(1)
    expect(failures[0].code).toBe('team_parse_failed')
  })
})
