import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { InstallError, initRole, installRoles, installTeamDefinitions, migrateTeams } from '../src/install.js'
import { parseRoleMarkdown } from '../src/role/parse.js'
import { parseTeamMarkdown } from '../src/team/parse.js'
import { activateTeam } from '../src/team/activate.js'
import type { RoleDefinition } from '../src/types.js'

function makeTmp(): string {
  return join(tmpdir(), `prism-agents-install-${Date.now()}-${Math.random().toString(36).slice(2)}`)
}

const ROLE_RAW = [
  '---',
  'name: "dev-1"',
  'description: "一般开发：常规功能开发。适用于：功能编码。不适用于：架构攻关（升级 super-dev）。"',
  'color: cyan',
  'model: "custom:builtin%3Abigmodel-coding-plan:GLM-5.3-Flash"',
  'thoughtLevel: max',
  'injectAgentsMd: true',
  '---',
  '',
  '# 一般开发 dev-1',
  '',
  '## 核心契约',
  '**交付可运行的增量，绝不扩大战场。**',
].join('\n')

const TEAM_RAW = [
  '---',
  'team_id: core-dev',
  'name: 核心研发团队',
  'description: 负责设计、开发、测试与质量收口。',
  'default: false',
  'members:',
  '  - role: dev-1',
  '    count: 2',
  '  - role: tester',
  '    count: 1',
  'skills: []',
  'knowledge:',
  '  layers: [global, project]',
  'deposit:',
  '  enabled: true',
  '  default_layer: project',
  '  default_type: pitfall',
  '  priority: medium',
  '  require_note: true',
  'arbitration: [safety, quality]',
  'rework_limit: 2',
  '---',
  '',
  '## 工作流',
].join('\n')

describe('installRoles（design-v3 §5 / harness §8 冲突策略）', () => {
  let targetDir = ''
  let sourceDir = ''
  let role: RoleDefinition

  beforeEach(() => {
    targetDir = makeTmp()
    sourceDir = makeTmp()
    mkdirSync(sourceDir, { recursive: true })
    const src = join(sourceDir, 'dev-1.md')
    writeFileSync(src, ROLE_RAW)
    role = parseRoleMarkdown(readFileSync(src, 'utf8'), { sourcePath: src })
  })
  afterEach(() => {
    /* 临时目录留给系统清理，避免 Windows 句柄问题 */
  })

  it('情况 1：目标文件不存在 → 写入（目录不存在也自动创建）', async () => {
    const nested = join(targetDir, 'agents', 'sub')
    const result = await installRoles({ targetDir: nested, roles: [role] })
    const path = join(nested, 'dev-1.md')
    expect(result.written).toEqual([path])
    expect(result.skipped).toEqual([])
    const content = readFileSync(path, 'utf8')
    expect(content).toContain('## 核心契约')
    expect(content.trimEnd().endsWith('<!-- generated by prism (role: dev-1) -->')).toBe(true)
  })

  it('情况 2：目标文件含 Prism marker → 覆盖', async () => {
    await installRoles({ targetDir, roles: [role] })
    const updated: RoleDefinition = { ...role, description: role.description + '（v2）' }
    const result = await installRoles({ targetDir, roles: [updated] })
    expect(result.written).toHaveLength(1)
    expect(result.skipped).toHaveLength(0)
    expect(readFileSync(join(targetDir, 'dev-1.md'), 'utf8')).toContain('（v2）')
  })

  it('情况 3：目标文件人写的（无 marker）→ 不覆盖，写 .prism-new 并记 skipped', async () => {
    const humanPath = join(targetDir, 'dev-1.md')
    mkdirSync(targetDir, { recursive: true })
    writeFileSync(humanPath, '---\nname: dev-1\ndescription: 人写的角色\n---\n\n## 核心契约\n**人写的原则。**\n')
    const result = await installRoles({ targetDir, roles: [role] })
    expect(result.written).toHaveLength(0)
    expect(result.skipped).toHaveLength(1)
    expect(result.skipped[0].path).toBe(humanPath)
    expect(result.skipped[0].reason).toContain('人编写')
    // 原文件未被覆盖；新版本落在 .prism-new 供对比
    expect(readFileSync(humanPath, 'utf8')).toContain('人写的角色')
    const prismNew = `${humanPath}.prism-new`
    expect(existsSync(prismNew)).toBe(true)
    expect(readFileSync(prismNew, 'utf8')).toContain('<!-- generated by prism (role: dev-1) -->')
  })

  it('--force：人写的文件也一律覆盖（不产生 .prism-new）', async () => {
    const humanPath = join(targetDir, 'dev-1.md')
    mkdirSync(targetDir, { recursive: true })
    writeFileSync(humanPath, '---\nname: dev-1\ndescription: 人写的角色\n---\n\n人写正文\n')
    const result = await installRoles({ targetDir, roles: [role], force: true })
    expect(result.written).toHaveLength(1)
    expect(result.skipped).toHaveLength(0)
    expect(readFileSync(humanPath, 'utf8')).toContain('## 核心契约')
    expect(existsSync(`${humanPath}.prism-new`)).toBe(false)
  })

  it('幂等：内容一致时不重写，报 skipped（reason=内容一致）', async () => {
    await installRoles({ targetDir, roles: [role] })
    const first = readFileSync(join(targetDir, 'dev-1.md'), 'utf8')
    const result = await installRoles({ targetDir, roles: [role] })
    expect(result.written).toHaveLength(0)
    expect(result.skipped).toHaveLength(1)
    expect(result.skipped[0].reason).toContain('内容一致')
    expect(readFileSync(join(targetDir, 'dev-1.md'), 'utf8')).toBe(first)
  })

  it('目标目录不可用（路径被文件占用）→ InstallError(install_failed) 可读错误', async () => {
    const blocked = makeTmp()
    mkdirSync(blocked, { recursive: true })
    const asFile = join(blocked, 'occupied') // 该路径是文件，不能作为目录创建
    writeFileSync(asFile, 'x')
    await expect(installRoles({ targetDir: join(asFile, 'agents'), roles: [role] })).rejects.toThrow(InstallError)
    try {
      await installRoles({ targetDir: join(asFile, 'agents'), roles: [role] })
    } catch (err) {
      expect((err as InstallError).code).toBe('install_failed')
      expect((err as InstallError).message).toContain('install_failed')
    }
  })

  it('env 覆盖环境属性：model/thoughtLevel 注入渲染产物（选项 B：环境填充）', async () => {
    await installRoles({ targetDir, roles: [role], env: { model: 'custom:other-model', thoughtLevel: 'high' } })
    const content = readFileSync(join(targetDir, 'dev-1.md'), 'utf8')
    expect(content).toContain('model: "custom:other-model"')
    expect(content).toContain('thoughtLevel: high')
  })

  it('渲染产物可被原样解析回等价角色定义（装配 ∘ 导入 往返）', async () => {
    await installRoles({ targetDir, roles: [role] })
    const round = parseRoleMarkdown(readFileSync(join(targetDir, 'dev-1.md'), 'utf8'))
    const expected: RoleDefinition = { ...role }
    delete expected.sourcePath // 往返不携带来源标注
    expect(round.name).toBe(expected.name)
    expect(round.description).toBe(expected.description)
    expect(round.model).toBe(expected.model)
    expect(round.thoughtLevel).toBe(expected.thoughtLevel)
    expect(round.injectAgentsMd).toBe(expected.injectAgentsMd)
    expect(round.principle).toBe(expected.principle)
    expect(round.skills).toEqual(expected.skills)
    expect(round.knowledge).toEqual(expected.knowledge)
    expect(round.body.startsWith(expected.body)).toBe(true) // 叠加层追加其后
  })
})

describe('installTeamDefinitions（团队定义落盘 <targetDir>/teams/）', () => {
  it('写入 teams/<team_id>.md，含团队 marker；渲染往返成立', async () => {
    const targetDir = makeTmp()
    const team = parseTeamMarkdown(TEAM_RAW)
    const result = await installTeamDefinitions({ targetDir, teams: [team] })
    const path = join(targetDir, 'teams', 'core-dev.md')
    expect(result.written).toEqual([path])
    const content = readFileSync(path, 'utf8')
    expect(content.trimEnd().endsWith('<!-- generated by prism (team: core-dev) -->')).toBe(true)
    const round = parseTeamMarkdown(content)
    expect(round.team_id).toBe('core-dev')
    expect(round.members).toEqual(team.members)
  })

  it('人写的团队文件同样不覆盖，记 skipped', async () => {
    const targetDir = makeTmp()
    const humanTeam = join(targetDir, 'teams', 'core-dev.md')
    mkdirSync(join(targetDir, 'teams'), { recursive: true })
    writeFileSync(humanTeam, '---\nteam_id: core-dev\nname: 人写团队\ndescription: 手工维护\n---\n')
    const result = await installTeamDefinitions({ targetDir, teams: [parseTeamMarkdown(TEAM_RAW)] })
    expect(result.skipped).toHaveLength(1)
    expect(existsSync(`${humanTeam}.prism-new`)).toBe(true)
  })
})

describe('activateTeam（装配语义简化：installed = roles_dir 中存在角色文件）', () => {
  it('roles_dir 即宿主目录：文件存在 → native；缺失 → fallback + definition + hint', async () => {
    const rolesDir = makeTmp()
    mkdirSync(rolesDir, { recursive: true })
    const team = parseTeamMarkdown(TEAM_RAW)
    // dev-1 扁平住在 roles_dir；tester 目录式住在 roles_dir
    writeFileSync(join(rolesDir, 'dev-1.md'), ROLE_RAW)
    mkdirSync(join(rolesDir, 'tester'))
    writeFileSync(
      join(rolesDir, 'tester', 'AGENTS.md'),
      ROLE_RAW.replace('name: "dev-1"', 'name: "tester"').replace('# 一般开发 dev-1', '# 测试 tester'),
    )

    const activation = await activateTeam(team, { rolesDir })
    expect(activation.team_id).toBe('core-dev')
    expect(activation.rework_limit).toBe(2)
    expect(activation.workflow).toEqual(team.workflow)

    const dev1 = activation.members.find((m) => m.role === 'dev-1')
    expect(dev1?.installed).toBe(true)
    expect(dev1?.dispatch).toBe('native')

    const tester = activation.members.find((m) => m.role === 'tester')
    expect(tester?.installed).toBe(true) // 目录式形态也算"存在"
    expect(tester?.dispatch).toBe('native')
    expect(tester?.definition?.name).toBe('tester')

    // 角色受管目录里不存在的成员：fallback + hint
    const ghostTeam = parseTeamMarkdown(TEAM_RAW.replace('- role: tester', '- role: ghost'))
    const ghostActivation = await activateTeam(ghostTeam, { rolesDir })
    const ghost = ghostActivation.members.find((m) => m.role === 'ghost')
    expect(ghost?.installed).toBe(false)
    expect(ghost?.dispatch).toBe('fallback')
    expect(ghost?.definition).toBeUndefined()
    expect(ghost?.hint).toContain('不存在')
  })

  it('兼容旧签名：显式 targetDir（旧复制语义落点）仍参与判定', async () => {
    const rolesDir = makeTmp()
    const targetDir = makeTmp()
    mkdirSync(rolesDir, { recursive: true })
    mkdirSync(targetDir, { recursive: true })
    const team = parseTeamMarkdown(TEAM_RAW)
    writeFileSync(join(rolesDir, 'dev-1.md'), ROLE_RAW) // 定义源
    await installRoles({ targetDir, roles: [parseRoleMarkdown(ROLE_RAW)] }) // 旧语义装配产物

    const activation = await activateTeam(team, { rolesDir, targetDir })
    const dev1 = activation.members.find((m) => m.role === 'dev-1')
    expect(dev1?.installed).toBe(true) // targetDir 兼容路径命中
    const tester = activation.members.find((m) => m.role === 'tester')
    expect(tester?.installed).toBe(false)
  })
})

describe('initRole（模板初始化：install 退化为模板初始化）', () => {
  it('模板 → roles_dir/<name>.md，{{name}} 替换；frontmatter 合法可解析', async () => {
    const rolesDir = makeTmp()
    const result = await initRole({ name: 'code-reviewer', rolesDir })
    const path = join(rolesDir, 'code-reviewer.md')
    expect(result.written).toEqual([path])
    const content = readFileSync(path, 'utf8')
    expect(content).toContain('name: "code-reviewer"')
    expect(content).not.toContain('{{name}}')
    const role = parseRoleMarkdown(content)
    expect(role.name).toBe('code-reviewer')
    expect(role.principle).toContain('TODO') // 模板原则留 TODO 提示待填（填前由人工/校验把关）
    expect(role.skills).toEqual([]) // 模板缺省空白名单
    expect(role.knowledge.layers).toEqual(['global', 'project'])
  })

  it('已存在 → skipped 不覆盖；--force 覆盖；非 kebab 名 → InstallError', async () => {
    const rolesDir = makeTmp()
    await initRole({ name: 'dev-x', rolesDir })
    const path = join(rolesDir, 'dev-x.md')
    const original = readFileSync(path, 'utf8')
    const again = await initRole({ name: 'dev-x', rolesDir })
    expect(again.written).toHaveLength(0)
    expect(again.skipped).toHaveLength(1)
    expect(readFileSync(path, 'utf8')).toBe(original)

    const forced = await initRole({ name: 'dev-x', rolesDir, force: true, template: '---\nname: "{{name}}"\ndescription: v2\n---\n正文' })
    expect(forced.written).toEqual([path])
    expect(readFileSync(path, 'utf8')).toContain('v2')

    await expect(initRole({ name: 'Dev X', rolesDir })).rejects.toThrow(InstallError)
  })
})

describe('migrateTeams（旧 Prism 源目录 → teamsDir 一次性迁移）', () => {
  it('目录式源迁移为 teamsDir 扁平产物；幂等（二次迁移不再写）；源文件不删除', async () => {
    const fromDir = makeTmp()
    const teamsDir = makeTmp()
    mkdirSync(join(fromDir, 'mini'), { recursive: true })
    writeFileSync(join(fromDir, 'mini', 'AGENTS.md'), TEAM_RAW.replace('team_id: core-dev', 'team_id: mini'))
    mkdirSync(join(fromDir, 'core-dev'))
    writeFileSync(join(fromDir, 'core-dev', 'AGENTS.md'), TEAM_RAW)

    const first = await migrateTeams({ fromDir, teamsDir })
    expect(first.written.sort()).toEqual([join(teamsDir, 'core-dev.md'), join(teamsDir, 'mini.md')])
    expect(first.migrated.map((t) => t.team_id).sort()).toEqual(['core-dev', 'mini'])
    expect(existsSync(join(fromDir, 'mini', 'AGENTS.md'))).toBe(true) // 源不删（由 init/用户清理）

    const second = await migrateTeams({ fromDir, teamsDir })
    expect(second.written).toHaveLength(0) // 幂等：内容一致不重复写
    expect(second.skipped).toHaveLength(2)
    expect(second.skipped.every((s) => s.reason.includes('内容一致'))).toBe(true)
  })
})
