/**
 * v16 B-4（R-4）：Prism 尾部 marker 的**累积**修复。
 *
 * 两条独立机制（都不是「正则太弱」）：
 * - ① 正文入口带旧 marker：`splitFrontmatter` 的 body 尾部含旧 marker（`patch.body` 未给时），
 *   overlay 注入把 marker 埋进中段——此后尾部正则再也够不着它；
 * - ② 中段 marker 被 `parseRoleMarkdown` 读回（它只剥**尾部**一枚），随 UI 的 body 快照再次落盘。
 * 两者叠加 = 「替换**非末位**小节时，尾 marker 落进被保留的 tail 段」→ 每次 PATCH 净 +1
 * （实测 2 → 3 → 4 → 5）。
 *
 * 修法：`patchRoleRaw` / `patchTeamRaw` 的**两个正文入口**（splitFrontmatter 的 body 与
 * `patch.body`）各自就地 `stripAllMarkerTails()` 剥净尾部，末尾再 append 一枚 fresh marker
 * （幂等单 marker）。
 *
 * 边界（R7）：自愈只覆盖**尾部**。历史文件里被 overlay 埋进中段的残留无法在纯文本层安全回收
 * （需结构化解析正文定位归属小节）——本轮只保证它**稳定 +1 不再增长**（SPEC-4.7）。
 *
 * 纯函数 + 临时目录（R5）；无平台判定。
 */

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { afterEach, describe, expect, it } from 'vitest'

import { splitFrontmatter, stripAllMarkerTails } from '../src/frontmatter.js'
import { editRole, patchRoleRaw } from '../src/role/write.js'
import { parseWorkflowSection } from '../src/team/parse.js'
import { patchTeamRaw } from '../src/team/write.js'
import type { WorkflowSerializeRow } from '../src/types.js'

const FIXTURES = fileURLToPath(new URL('./fixtures/team-workflow/', import.meta.url))
function fixture(name: string): string {
  return readFileSync(join(FIXTURES, name), 'utf8')
}

const RM = '<!-- generated by prism (role: r1) -->'
const TM = '<!-- generated by prism (team: delivery) -->'

/** Prism 产物 marker 的枚数（role/team 通用）。 */
function countMarkers(md: string): number {
  return (md.match(/<!-- generated by prism \((?:role|team): /g) ?? []).length
}

/** 正文（已剥 frontmatter）——与 patch 一致地丢掉前导空行，便于逐字节比对。 */
function bodyOf(md: string): string {
  return stripAllMarkerTails(splitFrontmatter(md).body).replace(/^\n+/, '')
}

/** 取 `## 工作流` 小节的有意义文本（去空行/行尾空白）——「正文不动」的判据（同 team-write.test.ts）。 */
function meaningfulWorkflowSection(md: string): string {
  const lines = md.replace(/\r\n/g, '\n').split('\n')
  const start = lines.findIndex((line) => line.trim() === '## 工作流')
  if (start === -1) return ''
  let end = lines.length
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].startsWith('## ')) {
      end = i
      break
    }
  }
  return lines
    .slice(start, end)
    .map((line) => line.trimEnd())
    .filter((line) => line.trim() !== '')
    .join('\n')
}

/** 解析结果 → PATCH 提交形态（带 rowId，模拟「读 raw → 编辑 → 提交」）。 */
function toRows(parsed: ReturnType<typeof parseWorkflowSection>): WorkflowSerializeRow[] {
  const rowIds = parsed.raw?.rowIds ?? []
  return parsed.stages.map((stage, index) => ({
    rowId: rowIds[index],
    order: stage.order,
    stage: stage.stage,
    roles: stage.roles,
    mode: stage.mode,
    input: stage.input,
    output: stage.output,
    done: stage.done,
    reflow: stage.reflow,
  }))
}

/**
 * 宿主原生形态角色：无 frontmatter `skills`/`knowledge` 键 → 走 overlay 小节；
 * 两个小节都在（skills 在前）= 「替换非末位小节」的累积形态。
 */
function roleOverlayRaw(markers = 1, bodyTail = ''): string {
  return [
    '---',
    'name: r1',
    'description: 原始描述',
    '---',
    '',
    '# r1',
    '',
    '正文段落。',
    bodyTail,
    '## 能力（Skill 白名单）',
    '- old-skill',
    '',
    '## 知识绑定',
    '- layers: global',
    '',
    ...Array.from({ length: markers }, () => RM),
    '',
  ].join('\n')
}

const tmpDirs: string[] = []
function makeTmp(): string {
  const dir = mkdtempSync(join(tmpdir(), 'prism-marker-'))
  tmpDirs.push(dir)
  return dir
}

afterEach(() => {
  while (tmpDirs.length > 0) rmSync(tmpDirs.pop()!, { recursive: true, force: true })
})

// ---------------------------------------------------------------------------

describe('SPEC-4.1 不累积（连打 PATCH，正文不动）', () => {
  it('重复替换**非末位**小节（skills）→ 每轮恰一枚（修前 2,3,4）', () => {
    let cur = roleOverlayRaw()
    const counts: number[] = []
    for (let i = 0; i < 3; i++) {
      cur = patchRoleRaw(cur, { skills: [`s${i + 1}`] })
      counts.push(countMarkers(cur))
    }
    expect(counts).toEqual([1, 1, 1])
    expect(cur.trimEnd().endsWith(RM)).toBe(true)
  })

  it('只改 frontmatter（不动 body）→ 尾 marker 恰一枚（修前 2,3,4）', () => {
    let cur = roleOverlayRaw()
    for (let i = 0; i < 3; i++) cur = patchRoleRaw(cur, { description: `d${i}` })
    expect(countMarkers(cur)).toBe(1)
    expect(cur).toContain('description: d2')
  })

  it('overlay 注入后 marker 不在中段：正文里没有 marker', () => {
    const next = patchRoleRaw(roleOverlayRaw(), { skills: ['s1'], knowledge: { layers: ['role'] } })
    expect(countMarkers(splitFrontmatter(next).body)).toBe(1)
    expect(next).toContain('## 能力（Skill 白名单）\n- s1')
    expect(next).toContain('## 知识绑定\n- layers: role')
  })
})

describe('SPEC-4.2 自愈（预置旧累积 → 一次 PATCH 收敛）', () => {
  it('尾部三枚旧 marker → 一次 PATCH 后恰一枚', () => {
    const raw = roleOverlayRaw(3)
    expect(countMarkers(raw)).toBe(3)
    const next = patchRoleRaw(raw, { description: 'd2' })
    expect(countMarkers(next)).toBe(1)
    expect(next.trimEnd().endsWith(RM)).toBe(true)
  })

  it('stripAllMarkerTails：循环剥净，且与既有 oracle 正则逐例等价', () => {
    // oracle = cli/test/role-new.test.ts:38 的既有正则（本仓对「尾部多枚 marker」的既有判据）
    const oracle = (s: string): string =>
      s.replace(/(?:\s*<!-- generated by prism \((?:role|team): [^)]*\) -->\s*)+$/, '').trimEnd()
    const cases = [
      `x\n${RM}\n`,
      `${RM}\n${RM}\n${RM}\n`,
      `${RM}\n${RM}`,
      `x\n${RM}`,
      `x\n${TM}\n${RM}\n`,
      'x\n',
      '',
      `${RM}\n正文\n${RM}\n`,
    ]
    for (const input of cases) {
      expect(stripAllMarkerTails(input), `case=${JSON.stringify(input)}`).toBe(oracle(input))
    }
  })
})

describe('SPEC-4.3 无 marker 不加（hadMarker 仍是 raw.includes 语义）', () => {
  it('人写文件（无 marker）→ 三种补丁形态都不追加 maker', () => {
    const raw = roleOverlayRaw(0)
    expect(patchRoleRaw(raw, { description: 'd2' })).not.toContain('generated by prism')
    expect(patchRoleRaw(raw, { skills: ['s1'] })).not.toContain('generated by prism')
    expect(patchRoleRaw(raw, { body: '# 全新正文\n' })).not.toContain('generated by prism')
  })

  it('team：无 marker 的团队文件 → PATCH 后仍无 marker', () => {
    const md = fixture('standard-8col.md').trimEnd() + '\n'
    const { markdown } = patchTeamRaw(md, { description: '改述' })
    expect(countMarkers(markdown)).toBe(0)
  })
})

describe('SPEC-4.4 正文不损（剥离只动尾部 marker 行）', () => {
  it('中段 marker 形态的行不是尾部 → 原位不动；正文其余字节不变', () => {
    const raw = ['---', 'name: r1', 'description: d', '---', '', '# r1', '', RM, '', '段落二。', '', RM, ''].join('\n')
    const next = patchRoleRaw(raw, { description: 'd2' })
    expect(countMarkers(next)).toBe(2) // 中段那枚保留 + 尾部一枚 fresh
    expect(next).toContain(`# r1\n\n${RM}\n\n段落二。`)
    expect(bodyOf(next)).toBe(bodyOf(raw))
  })

  it('正文里的「像 marker 但不在尾部」的行不被吃（含其后的空行与原样句）', () => {
    const raw = roleOverlayRaw(1, `引用了 ${RM} 这行说明。\n\n`)
    const next = patchRoleRaw(raw, { skills: ['s1'] })
    expect(next).toContain(`引用了 ${RM} 这行说明。`)
    expect(countMarkers(next)).toBe(2)
  })
})

describe('SPEC-4.5 有 marker + 替换正文 → 仍恰一枚（两入口就地剥）', () => {
  it('旧文件有 marker + 本次给 body → 恰一枚（修前即绿：旧 marker 仍在尾、未埋中段）', () => {
    const next = patchRoleRaw(roleOverlayRaw(), { body: '# 新正文\n\n换了。\n', skills: ['s1'] })
    expect(countMarkers(next)).toBe(1)
    expect(next).toContain('# 新正文')
    expect(next).not.toContain('正文段落。')
    expect(next.trimEnd().endsWith(RM)).toBe(true)
  })

  it('客户端回传的 body 自带尾 marker（含多枚）→ 入口②剥净，恰一枚', () => {
    const next = patchRoleRaw(roleOverlayRaw(), { body: `# 新正文\n\n${RM}\n${RM}\n` })
    expect(countMarkers(next)).toBe(1)
    expect(next).toContain('# 新正文')
  })
})

describe('SPEC-4.6 连打三次 overlay 补丁 → 恰一枚（中段埋入根因闭环）', () => {
  it('role：skills / knowledge 交替三次 → 恰一枚', () => {
    let cur = roleOverlayRaw()
    for (let i = 0; i < 3; i++) {
      cur = patchRoleRaw(cur, i % 2 === 0 ? { skills: ['s1'] } : { knowledge: { layers: ['global'] } })
    }
    expect(countMarkers(cur)).toBe(1)
    expect(cur.trimEnd().endsWith(RM)).toBe(true)
  })

  it('role：经 editRole 真实落盘，三次 PATCH 后文件尾恰一枚（R5 临时目录）', async () => {
    const rolesDir = makeTmp()
    const path = join(rolesDir, 'r1.md')
    writeFileSync(path, roleOverlayRaw(), 'utf8')
    for (let i = 0; i < 3; i++) {
      await editRole({ name: 'r1', rolesDir, patch: i % 2 === 0 ? { skills: ['s1'] } : { description: `d${i}` } })
    }
    const onDisk = readFileSync(path, 'utf8')
    expect(countMarkers(onDisk)).toBe(1)
    expect(onDisk.trimEnd().endsWith(RM)).toBe(true)
  })

  it('team：连打三次 workflow PATCH → 恰一枚', () => {
    let md = fixture('standard-8col.md').trimEnd() + `\n\n${TM}\n`
    for (let i = 0; i < 3; i++) {
      const rows = toRows(parseWorkflowSection(md)).map((row, index) => ({ ...row, order: index + 1, input: `i${i}` }))
      md = patchTeamRaw(md, { workflow: { stages: rows } }).markdown
    }
    expect(countMarkers(md)).toBe(1)
    expect(md.trimEnd().endsWith(TM)).toBe(true)
  })

  it('team：尾 marker 不进行号基准——identity 保存后表格区逐行不变', () => {
    // `bodyLineOffset` 靠「body 与第三参的长度差」反推行号偏移；若把尾 marker 算进去，
    // headerLine/lastLine 会整体错位 → 表格区 splice 落到错误行号上（正文被吃掉/错行）。
    const md = fixture('mixed-content.md').trimEnd() + `\n\n${TM}\n`
    const before = meaningfulWorkflowSection(md)
    const { markdown } = patchTeamRaw(md, { workflow: { stages: toRows(parseWorkflowSection(md)) } })
    expect(countMarkers(markdown)).toBe(1)
    expect(meaningfulWorkflowSection(markdown)).toBe(before)
    expect(markdown).toContain('下一小节正文。') // 表后正文存活（行号没错位）
  })
})

describe('SPEC-4.7 自愈边界：历史中段残留稳定 +1，不再增长', () => {
  it('中段残留 + 尾部 marker → 连续 PATCH 后枚数恒定（修前 3,4,5）', () => {
    const raw = ['---', 'name: r1', 'description: d', '---', '', '# 正文', '', RM, '', '更多正文。', '', RM, ''].join('\n')
    let cur = raw
    const counts: number[] = []
    for (let i = 0; i < 3; i++) {
      cur = patchRoleRaw(cur, { description: `d${i}` })
      counts.push(countMarkers(cur))
    }
    expect(counts).toEqual([2, 2, 2]) // = 1 枚中段残留（文本层无法安全回收）+ 1 枚尾部 fresh
    expect(cur).toContain(`# 正文\n\n${RM}\n\n更多正文。`) // 中段那枚原位不动
  })
})
