import { describe, expect, it } from 'vitest'

import { parseTeamMarkdown } from '../src/team/parse.js'
import { renderTeamScaffold, parseMembersSpec } from '../src/team/init.js'
import { validateTeam } from '../src/team/validate.js'
import type { RoleDefinition, TeamDefinition } from '../src/types.js'

/** 最小 RoleDefinition 桩（形状自检用）。 */
function role(name: string): RoleDefinition {
  return { name, description: '', skills: [], knowledge: { layers: ['global'] }, principle: '', body: '' }
}

/** `renderTeamScaffold` 的输出必须能被 parse 回来（round-trip）。 */
function roundTrip(markdown: string): TeamDefinition {
  return parseTeamMarkdown(markdown)
}

describe('renderTeamScaffold（F-C1）', () => {
  it('minimal 模板：渲染 → parse 往返 + validateTeam 通过（角色库齐备时零 error）', () => {
    const { markdown, issues } = renderTeamScaffold({ teamId: 'demo-team', teamsDir: '/tmp/teams' })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    const team = roundTrip(markdown)
    expect(team.team_id).toBe('demo-team')
    expect(team.name).toBe('demo-team') // 缺省 name = teamId
    expect(team.description).not.toBe('') // 缺省描述非空（否则校验不过）
    expect(team.members).toEqual([
      { role: 'dev-1', count: 1 },
      { role: 'tester', count: 1 },
    ])
    expect(team.workflow.map((s) => s.stage)).toEqual(['开发', '测试', '收口'])
    // 带真实角色库复跑：无 error（收口阶段由编排角色「队长」承担 → 豁免）
    const result = validateTeam(team, { roles: [role('dev-1'), role('tester')] })
    expect(result.ok).toBe(true)
    // 扁平形态 + Prism marker
    expect(markdown).toContain('<!-- generated by prism (team: demo-team) -->')
  })

  it('--name/--description 生效；描述含冒号与引号也不破坏结构', () => {
    const { markdown } = renderTeamScaffold({
      teamId: 'demo-team',
      teamsDir: '/tmp/teams',
      name: '演示团队',
      description: '负责演示：含"引号"与: 冒号。',
    })
    const team = roundTrip(markdown)
    expect(team.name).toBe('演示团队')
    expect(team.description).toBe('负责演示：含"引号"与: 冒号。')
    expect(markdown).toContain('# 演示团队') // 正文标题用原文，不加引号
  })

  it('team_id 非 kebab-case → team_id_invalid（error）且不渲染', () => {
    for (const bad of ['Demo', 'demo_team', '-demo', 'demo team', '']) {
      const out = renderTeamScaffold({ teamId: bad, teamsDir: '/tmp/teams' })
      expect(out.markdown).toBe('')
      expect(out.issues.some((i) => i.level === 'error' && i.code === 'team_id_invalid')).toBe(true)
    }
  })

  it('--members 覆盖模板成员（含 count 缺省=1）', () => {
    const { members } = parseMembersSpec('dev-1,tester:2')
    expect(members).toEqual([
      { role: 'dev-1', count: 1 },
      { role: 'tester', count: 2 },
    ])
    const { markdown, issues } = renderTeamScaffold({ teamId: 'demo-team', teamsDir: '/tmp', members })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    expect(roundTrip(markdown).members).toEqual(members)
  })

  it('单成员团队（--members dev-1）→ 工作流按名册收窄（剔除 tester 阶段）且零 error', () => {
    const { members } = parseMembersSpec('dev-1')
    const { markdown, issues } = renderTeamScaffold({ teamId: 'solo', teamsDir: '/tmp', members })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    // 收窄留痕（warning，不阻断落盘）
    expect(issues.some((i) => i.code === 'workflow_pruned')).toBe(true)
    const team = roundTrip(markdown)
    expect(team.workflow.map((s) => s.stage)).toEqual(['开发', '收口'])
    expect(team.workflow.map((s) => s.order)).toEqual([1, 2]) // 重编号
    expect(validateTeam(team, { roles: [role('dev-1')] }).ok).toBe(true)
  })

  it('members 为空数组 → members_empty（error，调用方不得落盘）', () => {
    const { issues } = renderTeamScaffold({ teamId: 'demo-team', teamsDir: '/tmp', members: [] })
    expect(issues.some((i) => i.level === 'error' && i.code === 'members_empty')).toBe(true)
  })

  it('名册收窄后工作流引用只剩成员与编排角色（不会 workflow_role_unknown）', () => {
    const { issues, markdown } = renderTeamScaffold({
      teamId: 'demo-team',
      teamsDir: '/tmp',
      members: [{ role: 'super-dev', count: 1 }],
    })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    const team = roundTrip(markdown)
    // 开发/测试阶段被剔除（引用 dev-1/tester），收口阶段由编排角色「队长」承担 → 保留
    expect(team.workflow.map((s) => s.stage)).toEqual(['收口'])
  })

  it('--from 克隆：换 id/名，extends/skills/knowledge/deposit 原样保留', () => {
    const source: TeamDefinition = {
      team_id: 'parent-team',
      name: '父团队',
      description: '父团队描述。',
      default: false,
      extends: 'base-team',
      members: [{ role: 'dev-1', count: 1 }],
      skills: ['code_review'],
      knowledge: { layers: ['global', 'project'] },
      deposit: {
        enabled: true,
        default_layer: 'project',
        default_type: 'pitfall',
        priority: 'high',
        require_note: true,
        rules: [{ match: { type: 'rule' }, set: { layer: 'global' } }],
      },
      arbitration: ['requirement'],
      rework_limit: 3,
      workflow: [
        {
          order: 1,
          stage: '开发',
          roles: ['dev-1'],
          mode: 'serial',
          input: 'a',
          output: 'b',
          done: 'c',
          reflow: 'd',
        },
      ],
      body: '# 父团队\n\n## 工作流\n\n| # | 阶段 | 负责角色 | 串/并行 | 输入 | 输出 | 完成判定 | 回流路径 |\n| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n| 1 | 开发 | dev-1 | 串行 | a | b | c | d |\n',
    }
    const { markdown, issues } = renderTeamScaffold({
      teamId: 'child-team',
      teamsDir: '/tmp',
      from: source,
    })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    const team = roundTrip(markdown)
    expect(team.team_id).toBe('child-team')
    expect(team.name).toBe('父团队') // 未给 --name → 继承源
    expect(team.description).toBe('父团队描述。')
    expect(team.extends).toBe('base-team') // extends 保留
    expect(team.skills).toEqual(['code_review'])
    expect(team.deposit.priority).toBe('high')
    expect(team.rework_limit).toBe(3)
    expect(team.workflow.map((s) => s.stage)).toEqual(['开发'])
    expect(validateTeam(team, { roles: [role('dev-1')] }).ok).toBe(true)
  })

  it('--from + --name/--description/--members 全部覆盖', () => {
    const source = roundTrip(
      renderTeamScaffold({ teamId: 'src', teamsDir: '/tmp' }).markdown,
    )
    const { members } = parseMembersSpec('dev-1:2,tester')
    const { markdown } = renderTeamScaffold({
      teamId: 'dst',
      teamsDir: '/tmp',
      from: source,
      name: '目标团队',
      description: '目标描述。',
      members,
    })
    const team = roundTrip(markdown)
    expect(team.team_id).toBe('dst')
    expect(team.name).toBe('目标团队')
    expect(team.description).toBe('目标描述。')
    expect(team.members).toEqual(members)
    // 工作流未覆盖 → 沿用源（引用 dev-1/tester 仍在 members 内）
    expect(validateTeam(team, { roles: [role('dev-1'), role('tester')] }).ok).toBe(true)
  })

  it('未知模板 → team_template_unknown', () => {
    const out = renderTeamScaffold({
      teamId: 'demo',
      teamsDir: '/tmp',
      template: 'nope' as 'minimal',
    })
    expect(out.markdown).toBe('')
    expect(out.issues.some((i) => i.code === 'team_template_unknown')).toBe(true)
  })

  it('core-dev 模板：7 阶段 5 成员，结构自检零 error', () => {
    const { markdown, issues } = renderTeamScaffold({
      teamId: 'core-dev-x',
      teamsDir: '/tmp',
      template: 'core-dev',
    })
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
    const team = roundTrip(markdown)
    expect(team.workflow).toHaveLength(7)
    expect(team.members.map((m) => m.role)).toEqual(['dev-1', 'dev-2', 'super-dev', 'tester', 'qa-checker'])
    // `dev-1/2` 实例记号展开
    expect(team.workflow[0]?.roles).toEqual(['dev-1#1', 'dev-1#2'])
    expect(
      validateTeam(team, { roles: ['dev-1', 'dev-2', 'super-dev', 'tester', 'qa-checker'].map(role) }).ok,
    ).toBe(true)
  })

  it('渲染是纯函数（同输入两次调用逐字节一致，且不触盘）', () => {
    const a = renderTeamScaffold({ teamId: 'demo-team', teamsDir: '/tmp/teams' })
    const b = renderTeamScaffold({ teamId: 'demo-team', teamsDir: '/tmp/teams' })
    expect(a.markdown).toBe(b.markdown)
  })
})

describe('parseMembersSpec（F-C1）', () => {
  it('缺省 count=1；全角逗号/空格容错', () => {
    expect(parseMembersSpec('dev-1, tester').members).toEqual([
      { role: 'dev-1', count: 1 },
      { role: 'tester', count: 1 },
    ])
  })

  it('重复角色 → 后者胜', () => {
    expect(parseMembersSpec('dev-1:1,dev-1:3').members).toEqual([{ role: 'dev-1', count: 3 }])
  })

  it('非法 count / 空 role / 多冒号 → members_invalid', () => {
    for (const bad of ['dev-1:0', 'dev-1:-1', 'dev-1:x', ':2', 'dev-1:2:3', 'dev-1:1.5']) {
      const out = parseMembersSpec(bad)
      expect(out.issues.some((i) => i.code === 'members_invalid')).toBe(true)
    }
    expect(parseMembersSpec('   ').issues.some((i) => i.code === 'members_invalid')).toBe(true)
  })
})
