import { mkdtemp, readFile, readdir, rm, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { PrismError } from '@prism/core'

import { installSkills } from '../src/install.js'
import { hasPrismMarker } from '../src/marker.js'
import { listBuiltinSkills } from '../src/index.js'
import type { PrismSkill } from '../src/types.js'

function makeSkill(name: string, withMarker: boolean): PrismSkill {
  const marker = '<!-- generated by prism (skill: demo) -->'
  const body = `---\nname: ${name}\ndescription: "demo"\n---\n\n${withMarker ? `${marker}\n\n` : ''}# Demo\n`
  return { name, description: 'demo', content: body, builtin: false }
}

describe('installSkills（design-v3 §5 冲突策略；全部写临时目录）', () => {
  let target: string

  beforeEach(async () => {
    target = await mkdtemp(join(tmpdir(), 'prism-skills-install-'))
  })

  afterEach(async () => {
    await rm(target, { recursive: true, force: true }).catch(() => {})
  })

  it('全新安装：写 <targetDir>/<name>/SKILL.md，目录自动创建', async () => {
    const result = await installSkills({ targetDir: join(target, 'nested', 'skills'), skills: [makeSkill('demo', true)] })
    expect(result.written).toEqual([join(target, 'nested', 'skills', 'demo', 'SKILL.md')])
    expect(result.skipped).toHaveLength(0)
    const content = await readFile(result.written[0], 'utf-8')
    expect(hasPrismMarker(content)).toBe(true)
  })

  it('幂等重装：已有 Prism marker → 直接覆盖，无 skipped', async () => {
    await installSkills({ targetDir: target, skills: [makeSkill('demo', true)] })
    const again = await installSkills({ targetDir: target, skills: [makeSkill('demo', true)] })
    expect(again.skipped).toHaveLength(0)
    expect(again.written).toHaveLength(1)
  })

  it('人写的 skill（无 marker）→ 不覆盖，写 .prism-new 供对比并记入 skipped；--force 才覆盖', async () => {
    const file = join(target, 'demo', 'SKILL.md')
    await mkdir(join(target, 'demo'), { recursive: true })
    await writeFile(file, '---\nname: demo\ndescription: "人写的"\n---\n\n手写内容\n', 'utf-8')

    const first = await installSkills({ targetDir: target, skills: [makeSkill('demo', true)] })
    expect(first.written).toEqual([`${file}.prism-new`])
    expect(first.skipped).toHaveLength(1)
    expect(first.skipped[0].path).toBe(file)
    expect(first.skipped[0].reason).toContain('--force')
    expect(await readFile(file, 'utf-8')).toContain('人写的')

    const forced = await installSkills({ targetDir: target, skills: [makeSkill('demo', true)], force: true })
    expect(forced.skipped).toHaveLength(0)
    expect(await readFile(file, 'utf-8')).not.toContain('人写的')
  })

  it('installSkills 内置 prism skill 全链路：安装后通过 marker 判定可覆盖', async () => {
    const result = await installSkills({ targetDir: target, skills: listBuiltinSkills() })
    expect(result.skipped).toHaveLength(0)
    const content = await readFile(join(target, 'prism', 'SKILL.md'), 'utf-8')
    expect(content).toContain('name: prism')
    expect(hasPrismMarker(content)).toBe(true)
    expect(existsSync(join(target, 'prism', 'SKILL.md'))).toBe(true)
    expect(await readdir(target)).toContain('prism')
  })

  it('内置 prism skill 带 references/（渐进披露），安装后 7 个引用文件就位', async () => {
    await installSkills({ targetDir: target, skills: listBuiltinSkills() })
    const refs = await readdir(join(target, 'prism', 'references'))
    expect(refs.sort()).toEqual([
      'arch.md',
      'cli.md',
      'graph.md',
      'knowledge.md',
      'task.md',
      'team.md',
      'work.md',
    ])
  })

  it('附带文件路径越界（..）→ bad_request', async () => {
    const skill: PrismSkill = {
      ...makeSkill('evil', true),
      assets: [{ path: '../escape.md', content: 'x' }],
    }
    await expect(installSkills({ targetDir: target, skills: [skill] })).rejects.toMatchObject({
      code: 'bad_request',
    })
  })

  it('幂等重装：SKILL.md 是 Prism 产物时，附带文件一并更新（不误判为人写）', async () => {
    const skill: PrismSkill = {
      ...makeSkill('idem', true),
      assets: [{ path: 'references/a.md', content: '第一版' }],
    }
    await installSkills({ targetDir: target, skills: [skill] })
    expect(await readFile(join(target, 'idem', 'references', 'a.md'), 'utf-8')).toBe('第一版')

    // 再次安装（模拟升级）：内容更新，且不产生 .prism-new、不记 skipped
    const upgraded: PrismSkill = {
      ...skill,
      assets: [{ path: 'references/a.md', content: '第二版' }],
    }
    const result = await installSkills({ targetDir: target, skills: [upgraded] })
    expect(await readFile(join(target, 'idem', 'references', 'a.md'), 'utf-8')).toBe('第二版')
    expect(existsSync(join(target, 'idem', 'references', 'a.md.prism-new'))).toBe(false)
    expect(result.skipped).toHaveLength(0)
  })

  it('人写的 SKILL.md 不覆盖时，附带文件也不动（整体跳过）', async () => {
    await mkdir(join(target, 'guard', 'references'), { recursive: true })
    await writeFile(join(target, 'guard', 'SKILL.md'), '---\nname: guard\ndescription: "人写"\n---\n\n手写\n', 'utf-8')
    await writeFile(join(target, 'guard', 'references', 'a.md'), '人写的', 'utf-8')
    const skill: PrismSkill = {
      ...makeSkill('guard', true),
      assets: [{ path: 'references/a.md', content: 'Prism 版' }],
    }
    const result = await installSkills({ targetDir: target, skills: [skill] })
    // 主文件被拒 → 整体跳过，不碰任何附带文件
    expect(await readFile(join(target, 'guard', 'SKILL.md'), 'utf-8')).toContain('人写')
    expect(await readFile(join(target, 'guard', 'references', 'a.md'), 'utf-8')).toBe('人写的')
    expect(result.skipped).toHaveLength(1)
    expect(result.skipped[0]?.path).toContain('SKILL.md')
  })

  it('目标目录不可写（父路径是文件）→ PrismError 可读错误', async () => {
    const blocker = join(target, 'blocker')
    await writeFile(blocker, 'not a dir', 'utf-8')
    await expect(installSkills({ targetDir: join(blocker, 'skills'), skills: [makeSkill('demo', true)] })).rejects.toMatchObject(
      { name: 'PrismError', code: 'bad_request' },
    )
    await expect(installSkills({ targetDir: join(blocker, 'skills'), skills: [makeSkill('demo', true)] })).rejects.toBeInstanceOf(
      PrismError,
    )
  })
})
