import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { installSkills } from '../src/install.js'
import { uninstallSkills } from '../src/uninstall.js'
import { listBuiltinSkills } from '../src/index.js'
import type { PrismSkill } from '../src/types.js'

function makeSkill(name: string, withMarker: boolean): PrismSkill {
  const marker = `<!-- generated by prism (skill: ${name}) -->`
  const body = `---\nname: ${name}\ndescription: "demo"\n---\n\n${withMarker ? `${marker}\n\n` : ''}# Demo\n`
  return { name, description: 'demo', content: body, builtin: false }
}

describe('uninstallSkills（只删 Prism 产物；全部写临时目录）', () => {
  let target: string

  beforeEach(async () => {
    target = await mkdtemp(join(tmpdir(), 'prism-skills-uninstall-'))
  })

  afterEach(async () => {
    await rm(target, { recursive: true, force: true }).catch(() => {})
  })

  it('目录不存在 → 空结果（幂等：没什么可卸的）', async () => {
    const result = await uninstallSkills({ targetDir: join(target, 'nope') })
    expect(result).toEqual({ removed: [], kept: [] })
  })

  it('names 缺省 = 扫描目录下全部：Prism 产物删除、人写的保留、无 SKILL.md 的保留', async () => {
    await installSkills({ targetDir: target, skills: [makeSkill('mine', true)] })
    await mkdir(join(target, 'handwritten'), { recursive: true })
    await writeFile(join(target, 'handwritten', 'SKILL.md'), '---\nname: handwritten\n---\n\n手写\n', 'utf-8')
    await mkdir(join(target, 'empty-dir'), { recursive: true })

    const result = await uninstallSkills({ targetDir: target })
    expect(result.removed).toEqual(['mine'])
    expect(existsSync(join(target, 'mine'))).toBe(false)
    expect(existsSync(join(target, 'handwritten', 'SKILL.md'))).toBe(true)
    expect(existsSync(join(target, 'empty-dir'))).toBe(true)

    const keptNames = result.kept.map((k) => k.name).sort()
    expect(keptNames).toEqual(['empty-dir', 'handwritten'])
    expect(result.kept.find((k) => k.name === 'handwritten')?.reason).toContain('非 Prism 产物')
    expect(result.kept.find((k) => k.name === 'empty-dir')?.reason).toContain('无 SKILL.md')
  })

  it('names 指定 → 只处理点名的 Skill（其余原地不动）', async () => {
    await installSkills({ targetDir: target, skills: [makeSkill('a', true), makeSkill('b', true)] })
    const result = await uninstallSkills({ targetDir: target, names: ['a'] })
    expect(result.removed).toEqual(['a'])
    expect(existsSync(join(target, 'a'))).toBe(false)
    expect(existsSync(join(target, 'b', 'SKILL.md'))).toBe(true)
  })

  it('names 里的未知名字 → 记入 kept（无 SKILL.md），不报错', async () => {
    const result = await uninstallSkills({ targetDir: target, names: ['ghost'] })
    expect(result.removed).toEqual([])
    expect(result.kept).toEqual([{ name: 'ghost', path: join(target, 'ghost'), reason: '无 SKILL.md' }])
  })

  it('安装 → 卸载全链路：内置 prism skill（含 references/）整目录清除', async () => {
    await installSkills({ targetDir: target, skills: listBuiltinSkills() })
    expect(existsSync(join(target, 'prism', 'references', 'cli.md'))).toBe(true)

    const result = await uninstallSkills({ targetDir: target, names: ['prism'] })
    expect(result.removed).toEqual(['prism'])
    expect(existsSync(join(target, 'prism'))).toBe(false)
    expect(result.kept).toEqual([])
  })

  it('人写的 Skill 用 --force 装过（已带 marker）→ 可被卸载', async () => {
    // 先人造一个文件，再用 force 覆盖安装（写入带 marker 的 Prism 产物）
    await mkdir(join(target, 'demo'), { recursive: true })
    await writeFile(join(target, 'demo', 'SKILL.md'), '人写的\n', 'utf-8')
    await installSkills({ targetDir: target, skills: [makeSkill('demo', true)], force: true })
    expect(await readFile(join(target, 'demo', 'SKILL.md'), 'utf-8')).toContain('generated by prism')

    const result = await uninstallSkills({ targetDir: target, names: ['demo'] })
    expect(result.removed).toEqual(['demo'])
    expect(existsSync(join(target, 'demo'))).toBe(false)
  })
})
