import { describe, expect, it } from 'vitest'

import { prismSkill } from '../src/builtin/prism.js'
import { listBuiltinSkills } from '../src/index.js'
import { MAX_DESCRIPTION_LENGTH, validateSkill } from '../src/validate.js'
import type { PrismSkill } from '../src/types.js'

function makeSkill(overrides: Partial<PrismSkill> = {}): PrismSkill {
  return {
    name: 'demo-skill',
    description: '演示用 skill：当用户要求演示冲突策略时使用。',
    content: '---\nname: demo-skill\ndescription: "演示用 skill：当用户要求演示冲突策略时使用。"\n---\n\n# Demo\n\n正文。\n',
    builtin: false,
    ...overrides,
  }
}

describe('validateSkill（design-v3 §3.2 + skill-loading §4）', () => {
  it('正例：合法 skill 通过（ok=true，无 error）', () => {
    const result = validateSkill(makeSkill())
    expect(result.ok).toBe(true)
    expect(result.issues.filter((i) => i.level === 'error')).toHaveLength(0)
  })

  it('内置 prism skill 自身合法：name kebab-case、description ≤1024、含触发词', () => {
    const result = validateSkill(prismSkill)
    expect(result.ok).toBe(true)
    expect(prismSkill.name).toBe('prism')
    expect(prismSkill.description.length).toBeLessThanOrEqual(MAX_DESCRIPTION_LENGTH)
    // 触发词（设计要求 description 含触发词）
    expect(prismSkill.description).toContain('知识')
    expect(prismSkill.description).toContain('团队')
  })

  it('listBuiltinSkills 返回内置 skill（builtin=true）', () => {
    const skills = listBuiltinSkills()
    expect(skills.length).toBeGreaterThanOrEqual(1)
    expect(skills.map((s) => s.name)).toContain('prism')
    for (const skill of skills) {
      expect(skill.builtin).toBe(true)
      expect(skill.content).toContain('generated by prism')
    }
  })

  it('反例：缺 name → error', () => {
    const result = validateSkill(makeSkill({ name: '' }))
    expect(result.ok).toBe(false)
    expect(result.issues.some((i) => i.code === 'skill_name_missing')).toBe(true)
  })

  it('反例：name 非 kebab-case（大写/下划线/空格/首尾连字符）→ error', () => {
    for (const bad of ['Demo', 'demo_skill', 'demo skill', '-demo', 'demo-']) {
      const result = validateSkill(makeSkill({ name: bad }))
      expect(result.ok, bad).toBe(false)
      expect(result.issues.some((i) => i.code === 'skill_name_invalid'), bad).toBe(true)
    }
  })

  it('反例：缺 description → error；超 1024 字符 → error', () => {
    const missing = validateSkill(makeSkill({ description: '' }))
    expect(missing.ok).toBe(false)
    expect(missing.issues.some((i) => i.code === 'skill_description_missing')).toBe(true)

    const tooLong = validateSkill(makeSkill({ description: '长'.repeat(MAX_DESCRIPTION_LENGTH + 1) }))
    expect(tooLong.ok).toBe(false)
    expect(tooLong.issues.some((i) => i.code === 'skill_description_too_long')).toBe(true)
  })

  it('反例：content 为空 / 无 frontmatter → error', () => {
    const empty = validateSkill(makeSkill({ content: '' }))
    expect(empty.ok).toBe(false)
    expect(empty.issues.some((i) => i.code === 'skill_content_missing')).toBe(true)

    const noFm = validateSkill(makeSkill({ content: '# 没有 frontmatter\n\n正文。\n' }))
    expect(noFm.ok).toBe(false)
    expect(noFm.issues.some((i) => i.code === 'skill_frontmatter_missing')).toBe(true)
  })

  it('frontmatter 与字段不一致 → warning（不阻断 ok）', () => {
    const result = validateSkill(
      makeSkill({ content: '---\nname: other-name\ndescription: "别的描述"\n---\n\n正文\n' }),
    )
    expect(result.ok).toBe(true)
    expect(result.issues.filter((i) => i.level === 'warning').length).toBeGreaterThanOrEqual(2)
  })
})
