/**
 * agents 包独立 frontmatter 解析器（零依赖 YAML 子集）。
 *
 * **不复用 knowledge 的解析器**（design-v3 §3.1.1 P2：qa 实测其对嵌套映射 /
 * 序列-of-映射会结构损坏）。本实现按 §3.1.1 支持范围逐条实现：
 *
 * | 语法 | 示例 |
 * | :--- | :--- |
 * | 顶层标量 | `team_id: core-dev` |
 * | 引号标量（含冒号/特殊字符） | `name: "QA-checker"` |
 * | 多行折叠 `>` 与字面 `\|` | `description: >` + 缩进续行 |
 * | flow 数组 | `layers: [global, role]` |
 * | flow 映射 | `{ type: rule }` |
 * | 块式嵌套映射 | `knowledge:` + 缩进 `layers:` / `books:` |
 * | 块式序列-of-标量 | `skills:` + `- taint_trace` |
 * | 块式序列-of-映射 | `members:` + `- role: dev-1` + `count: 2` |
 * | 两层（及以上）嵌套映射 | `deposit:` + 缩进字段 |
 * | 序列-of-映射（规则） | `rules:` + `- match: {...}` + `set: {...}` |
 *
 * **不支持**（命中即抛 FrontmatterError，code = 'parse_unsupported'）：
 * 锚点/别名（`&`/`*`）、标签（`!`）、多文档（frontmatter 内再出现 `---`/`...`）、
 * 复杂键（`? `）、制表符缩进、带显式缩进指示数字的块式标量（如 `>2`）。
 */

export type FrontmatterValue =
  | string
  | number
  | boolean
  | null
  | FrontmatterValue[]
  | { [key: string]: FrontmatterValue }
export type FrontmatterData = Record<string, FrontmatterValue>

/** frontmatter 解析失败（语法不支持或结构非法）。 */
export class FrontmatterError extends Error {
  readonly code: 'parse_unsupported' | 'parse_failed'
  /** 1 起始的行号（相对 frontmatter 文本）。 */
  readonly line?: number

  constructor(code: 'parse_unsupported' | 'parse_failed', message: string, line?: number) {
    super(line === undefined ? `${code}: ${message}` : `${code} (line ${line}): ${message}`)
    this.name = 'FrontmatterError'
    this.code = code
    this.line = line
  }
}

/** 安全集：不加引号也不会被误读为其他类型的纯词（复用 knowledge emitScalar 的 SAFE_PLAIN 思路）。 */
const SAFE_PLAIN_RE = /^[A-Za-z0-9_][A-Za-z0-9_.\-/@()]*$/

/** Prism 产物尾部 marker（不属于正文；解析时剥掉，保证「导入 → 渲染」幂等）。 */
const MARKER_TAIL_RE = /\s*<!-- generated by prism \((?:role|team): [^)]*\) -->\s*$/

/** 剥掉文本尾部的 Prism marker 并收敛尾部空白。 */
export function stripPrismMarkerTail(body: string): string {
  return body.replace(MARKER_TAIL_RE, '').trimEnd()
}

/** 拆开 `---\n...\n---` 头与正文；无 frontmatter 时 data 为 null。 */
export function splitFrontmatter(raw: string): { data: FrontmatterData | null; body: string } {
  const normalized = raw.replace(/\r\n/g, '\n')
  if (!normalized.startsWith('---\n')) {
    return { data: null, body: normalized }
  }
  // 从 4 开始找终止行「\n---」（后随行尾/文件尾）；「\n----」这类主题分隔行不算
  let end = normalized.indexOf('\n---', 4)
  while (end !== -1) {
    const after = normalized.slice(end + 4)
    if (after === '' || after.startsWith('\n')) {
      const yaml = normalized.slice(4, end)
      const body = after.startsWith('\n') ? after.slice(1) : ''
      return { data: parseFrontmatter(yaml), body }
    }
    end = normalized.indexOf('\n---', end + 4)
  }
  // 有头无尾：交由上层报 no_frontmatter
  return { data: null, body: normalized }
}

// ---------------------------------------------------------------------------
// 解析
// ---------------------------------------------------------------------------

interface Line {
  /** 前导空格数。 */
  indent: number
  /** 去掉前导空白后的内容；空行为 ''。 */
  content: string
  /** 1 起始行号。 */
  num: number
}

/** 解析 frontmatter YAML 子集。语法不支持/结构非法时抛 FrontmatterError。 */
export function parseFrontmatter(yaml: string): FrontmatterData {
  const lines = toLines(yaml)
  const first = lines.findIndex((l) => l.content !== '')
  if (first === -1) return {}
  const { value, next } = parseNode(lines, first, lines[first].indent)
  const tail = lines.slice(next).find((l) => l.content !== '')
  if (tail) {
    throw new FrontmatterError('parse_failed', `第 ${tail.num} 行出现未预期的内容`, tail.num)
  }
  return value as FrontmatterData
}

function toLines(yaml: string): Line[] {
  const rawLines = yaml.replace(/\r\n/g, '\n').split('\n')
  const out: Line[] = []
  for (let i = 0; i < rawLines.length; i++) {
    const raw = rawLines[i]
    if (raw.trim() === '') {
      out.push({ indent: 0, content: '', num: i + 1 })
      continue
    }
    const lead = raw.length - raw.trimStart().length
    if (raw.slice(0, lead).includes('\t')) {
      throw new FrontmatterError('parse_unsupported', 'frontmatter 不支持制表符缩进', i + 1)
    }
    const trimmed = raw.trim()
    if (trimmed.startsWith('#')) continue
    if (trimmed === '---' || trimmed === '...') {
      throw new FrontmatterError('parse_unsupported', '不支持多文档 frontmatter', i + 1)
    }
    if (/^(\?|!!)/.test(trimmed)) {
      throw new FrontmatterError('parse_unsupported', `不支持的语法：${trimmed.slice(0, 12)}`, i + 1)
    }
    out.push({ indent: lead, content: stripComment(trimmed), num: i + 1 })
  }
  return out
}

/** 去掉行尾注释：引号外、且 `#` 前有空白才算注释。 */
function stripComment(line: string): string {
  let inQuote: string | null = null
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuote) {
      if (inQuote === "'" && ch === "'" && line[i + 1] === "'") i++
      else if (ch === inQuote) inQuote = null
      continue
    }
    if (ch === '"' || ch === "'") {
      inQuote = ch
      continue
    }
    if (ch === '#' && i > 0 && line[i - 1] === ' ') return line.slice(0, i).trimEnd()
  }
  return line
}

/** 在行序列上解析一个节点（映射或序列），返回值与消费后的下一索引。 */
function parseNode(lines: Line[], start: number, indent: number): { value: FrontmatterValue; next: number } {
  if (isSeqItem(lines[start].content)) {
    return parseBlockSeq(lines, start, indent)
  }
  return parseBlockMap(lines, start, indent)
}

function skipBlanks(lines: Line[], i: number): number {
  while (i < lines.length && lines[i].content === '') i++
  return i
}

/** 块式映射：`key: value` / `key:` + 更深缩进的子块 / `key: >` 多行标量。 */
function parseBlockMap(lines: Line[], start: number, indent: number): { value: FrontmatterValue; next: number } {
  const map: { [key: string]: FrontmatterValue } = {}
  let i = start
  while (i < lines.length) {
    i = skipBlanks(lines, i)
    if (i >= lines.length) break
    const line = lines[i]
    if (line.indent < indent) break
    if (line.indent > indent) {
      throw new FrontmatterError('parse_failed', `第 ${line.num} 行缩进异常（多了 ${line.indent - indent} 个空格）`, line.num)
    }
    if (isSeqItem(line.content)) break
    const sep = findKeySeparator(line.content)
    if (sep === -1) {
      throw new FrontmatterError('parse_failed', `第 ${line.num} 行不是合法的 key: value`, line.num)
    }
    const key = unquoteKey(line.content.slice(0, sep).trim())
    const rest = line.content.slice(sep + 1).trim()
    i++
    if (rest === '') {
      const j = skipBlanks(lines, i)
      // 空值：更深缩进的子块（映射或序列）/ 同缩进序列 / null
      if (j < lines.length && lines[j].indent > indent) {
        const child = parseNode(lines, j, lines[j].indent)
        map[key] = child.value
        i = child.next
      } else if (j < lines.length && lines[j].indent === indent && isSeqItem(lines[j].content)) {
        const seq = parseBlockSeq(lines, j, indent)
        map[key] = seq.value
        i = seq.next
      } else {
        map[key] = null
      }
      continue
    }
    const header = matchBlockScalarHeader(rest, line.num)
    if (header) {
      const parsed = parseBlockScalar(lines, i, indent, header, line.num)
      map[key] = parsed.value
      i = parsed.next
      continue
    }
    checkUnsupportedScalar(rest, line.num)
    map[key] = parseInlineValue(rest, line.num)
  }
  return { value: map, next: i }
}

/** 块式序列：`- item` / `- key: value`（映射项，可多行）/ `-` + 更深子块。 */
function parseBlockSeq(lines: Line[], start: number, indent: number): { value: FrontmatterValue; next: number } {
  const items: FrontmatterValue[] = []
  let i = start
  while (i < lines.length) {
    i = skipBlanks(lines, i)
    if (i >= lines.length) break
    const line = lines[i]
    if (line.indent !== indent || !isSeqItem(line.content)) break
    const rest = line.content === '-' ? '' : line.content.slice(1).trim()
    if (rest === '') {
      // `-` 单独成行：项是更深缩进的子块
      i++
      const j = skipBlanks(lines, i)
      if (j < lines.length && lines[j].indent > indent) {
        const child = parseNode(lines, j, lines[j].indent)
        items.push(child.value)
        i = child.next
      } else {
        items.push(null)
      }
      continue
    }
    // `- key: value` → 项是映射：剩余内容视作虚拟行（缩进 = 项内容列），连同后续行一起解析
    if (startsMapEntry(rest)) {
      const afterDash = line.content.slice(1)
      const lead = afterDash.length - afterDash.trimStart().length
      const innerIndent = indent + 1 + lead
      lines[i] = { indent: innerIndent, content: afterDash.trim(), num: line.num }
      const child = parseBlockMap(lines, i, innerIndent)
      items.push(child.value)
      i = child.next
      continue
    }
    checkUnsupportedScalar(rest, line.num)
    items.push(parseInlineValue(rest, line.num))
    i++
  }
  return { value: items, next: i }
}

function isSeqItem(content: string): boolean {
  return content === '-' || content.startsWith('- ')
}

/** rest 是否是 `key: ...` 形态（映射项首行；flow 集合/引号标量/块式标量头不算）。 */
function startsMapEntry(rest: string): boolean {
  if (rest.startsWith('{') || rest.startsWith('[') || rest.startsWith('"') || rest.startsWith("'")) return false
  if (matchBlockScalarHeader(rest) !== null) return false
  return findKeySeparator(rest) !== -1
}

// ---------------------------------------------------------------------------
// 多行块式标量（`>` 折叠 / `|` 字面）——仅支持作为映射值
// ---------------------------------------------------------------------------

interface BlockScalarHeader {
  style: '>' | '|'
  chomp: 'clip' | 'strip' | 'keep'
}

function matchBlockScalarHeader(rest: string, line?: number): BlockScalarHeader | null {
  const m = /^([>|])([+-]?)$/.exec(rest)
  if (!m) {
    if (/^[>|][0-9]/.test(rest)) {
      throw new FrontmatterError('parse_unsupported', `不支持带缩进指示数字的块式标量：${rest}`, line)
    }
    return null
  }
  const chomp = m[2] === '-' ? 'strip' : m[2] === '+' ? 'keep' : 'clip'
  return { style: m[1] as '>' | '|', chomp }
}

function parseBlockScalar(
  lines: Line[],
  start: number,
  keyIndent: number,
  header: BlockScalarHeader,
  headerLine: number,
): { value: FrontmatterValue; next: number } {
  const body: string[] = []
  let i = start
  let blockIndent = -1
  while (i < lines.length) {
    const line = lines[i]
    if (line.content === '') {
      body.push('')
      i++
      continue
    }
    if (line.indent <= keyIndent) break
    if (blockIndent === -1) blockIndent = line.indent
    if (line.indent < blockIndent) break
    body.push(' '.repeat(line.indent - blockIndent) + line.content)
    i++
  }
  if (blockIndent === -1) {
    throw new FrontmatterError('parse_failed', `第 ${headerLine} 行的块式标量没有内容`, headerLine)
  }
  let text: string
  if (header.style === '|') {
    text = body.join('\n')
  } else {
    // 折叠：非空行以空格连接；空行 → 换行
    text = ''
    for (const l of body) {
      if (l === '') {
        text += '\n'
      } else {
        text = text.endsWith('\n') || text === '' ? text + l : `${text} ${l}`
      }
    }
  }
  // chomping：clip = 恰一个结尾换行；strip = 无；keep = 原样保留
  const core = text.replace(/\n+$/, '')
  const trailing = text.length - core.length
  if (header.chomp === 'strip') text = core
  else if (header.chomp === 'clip') text = core === '' ? '' : `${core}\n`
  else text = core === '' ? text : core + '\n'.repeat(trailing)
  return { value: text, next: i }
}

// ---------------------------------------------------------------------------
// 行内标量 / flow 集合
// ---------------------------------------------------------------------------

/** 锚点/别名/标签检查（值或序列项起点）。 */
function checkUnsupportedScalar(text: string, line: number): void {
  if (/^[&*!]/.test(text)) {
    throw new FrontmatterError('parse_unsupported', `不支持的语法（锚点/别名/标签）：${text.slice(0, 16)}`, line)
  }
}

/** 解析行内值：标量 / flow 数组 / flow 映射。 */
function parseInlineValue(text: string, line: number): FrontmatterValue {
  const s = text.trim()
  if (s === '' || s === 'null' || s === '~' || s === 'Null' || s === 'NULL') return null
  if (s === 'true' || s === 'True' || s === 'TRUE') return true
  if (s === 'false' || s === 'False' || s === 'FALSE') return false
  if (s.startsWith('"')) return parseDoubleQuoted(s, line)
  if (s.startsWith("'")) return parseSingleQuoted(s, line)
  if (s.startsWith('[') && s.endsWith(']')) return parseFlowSeq(s, line)
  if (s.startsWith('{') && s.endsWith('}')) return parseFlowMap(s, line)
  if (/^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/.test(s)) return Number(s)
  if (/^0x[0-9a-fA-F]+$/.test(s)) return Number(s)
  return s
}

function parseDoubleQuoted(s: string, line: number): FrontmatterValue {
  if (!s.endsWith('"') || s.length < 2) {
    throw new FrontmatterError('parse_failed', `第 ${line} 行双引号标量未闭合`, line)
  }
  try {
    return JSON.parse(s) as FrontmatterValue
  } catch {
    // JSON 不接受的转义（如 \xNN）→ 明确不支持，而非静默错值
    throw new FrontmatterError('parse_unsupported', `第 ${line} 行双引号转义不受支持`, line)
  }
}

function parseSingleQuoted(s: string, line: number): FrontmatterValue {
  if (!s.endsWith("'") || s.length < 2) {
    throw new FrontmatterError('parse_failed', `第 ${line} 行单引号标量未闭合`, line)
  }
  return s.slice(1, -1).replace(/''/g, "'")
}

/** 解析行内 flow 数组：按不在引号/嵌套内的顶层逗号切分。 */
function parseFlowSeq(s: string, line: number): FrontmatterValue[] {
  const inner = s.slice(1, -1).trim()
  if (inner === '') return []
  return splitTopLevel(inner).map((p) => parseInlineValue(p, line))
}

/** 解析行内 flow 映射 `{k: v, ...}`。 */
function parseFlowMap(s: string, line: number): { [key: string]: FrontmatterValue } {
  const inner = s.slice(1, -1).trim()
  const out: { [key: string]: FrontmatterValue } = {}
  if (inner === '') return out
  for (const part of splitTopLevel(inner)) {
    const idx = findFlowKeySeparator(part)
    if (idx === -1) {
      throw new FrontmatterError('parse_failed', `flow 映射项缺少冒号：${part.slice(0, 20)}`, line)
    }
    const key = unquoteKey(part.slice(0, idx).trim())
    out[key] = parseInlineValue(part.slice(idx + 1).trim(), line)
  }
  return out
}

/** 按不在引号/嵌套括号内的顶层逗号切分。 */
function splitTopLevel(s: string): string[] {
  const parts: string[] = []
  let depth = 0
  let inQuote: string | null = null
  let current = ''
  for (const ch of s) {
    if (inQuote) {
      current += ch
      if (ch === inQuote) inQuote = null
      continue
    }
    if (ch === '"' || ch === "'") {
      inQuote = ch
      current += ch
      continue
    }
    if (ch === '[' || ch === '{') depth++
    if (ch === ']' || ch === '}') depth--
    if (ch === ',' && depth === 0) {
      parts.push(current.trim())
      current = ''
      continue
    }
    current += ch
  }
  if (current.trim() !== '') parts.push(current.trim())
  return parts
}

/** 找到 `key:` 分隔符：第一个不在引号/flow 括号内的 `:`（行尾冒号或后随空格）。 */
function findKeySeparator(text: string): number {
  let inQuote: string | null = null
  let depth = 0
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inQuote) {
      if (ch === inQuote) inQuote = null
      continue
    }
    if (ch === '"' || ch === "'") {
      inQuote = ch
      continue
    }
    if (ch === '[' || ch === '{') depth++
    if (ch === ']' || ch === '}') depth--
    if (ch === ':' && depth === 0 && (i + 1 === text.length || text[i + 1] === ' ')) return i
  }
  return -1
}

/** flow 映射里的 key 分隔（key 在前，取第一个引号外冒号即可）。 */
function findFlowKeySeparator(part: string): number {
  let inQuote: string | null = null
  for (let i = 0; i < part.length; i++) {
    const ch = part[i]
    if (inQuote) {
      if (ch === inQuote) inQuote = null
      continue
    }
    if (ch === '"' || ch === "'") {
      inQuote = ch
      continue
    }
    if (ch === ':') return i
  }
  return -1
}

function unquoteKey(key: string): string {
  if (key.length >= 2 && ((key.startsWith('"') && key.endsWith('"')) || (key.startsWith("'") && key.endsWith("'")))) {
    return key.slice(1, -1)
  }
  return key
}

// ---------------------------------------------------------------------------
// 序列化（渲染回写；serialize → parse 必须等价）
// ---------------------------------------------------------------------------

/** 序列化为 frontmatter 文本（含首尾 --- 行）。 */
export function serializeFrontmatter(data: FrontmatterData): string {
  const body = emitBlockMap(data, 0)
  return `---\n${body}\n---\n`
}

/** 生成完整 md 文件：frontmatter（自带结尾换行）+ 正文。 */
export function renderMarkdownFile(data: FrontmatterData, content: string): string {
  return `${serializeFrontmatter(data)}${content.endsWith('\n') || content === '' ? content : `${content}\n`}`
}

/**
 * 标量安全输出（harness §2.1 引号约束）：
 * 含冒号/特殊字符/看似数字或布尔/空串的值一律 JSON 双引号（合法的 YAML 双引号标量）。
 */
export function emitScalar(s: string): string {
  if (s === '') return '""'
  if (
    SAFE_PLAIN_RE.test(s) &&
    Number.isNaN(Number(s)) &&
    !['true', 'false', 'null', '~', 'True', 'False', 'Null'].includes(s)
  ) {
    return s
  }
  return JSON.stringify(s)
}

function emitBlockMap(data: FrontmatterData, indent: number): string {
  const pad = ' '.repeat(indent)
  const chunks: string[] = []
  for (const [key, value] of Object.entries(data)) {
    // 首行由这里补缩进；子行（嵌套块）已自带更深缩进
    chunks.push(pad + emitEntry(key, value, indent, pad))
  }
  return chunks.join('\n')
}

/** 单个 `key: value` 条目（可能展开为多行；首行**不带**缩进，由调用方补；子行已自带缩进）。 */
function emitEntry(key: string, value: FrontmatterValue, indent: number, pad: string): string {
  if (value === null) return `${key}: null`
  if (typeof value === 'string') return `${key}: ${emitScalar(value)}`
  if (typeof value === 'number' || typeof value === 'boolean') return `${key}: ${String(value)}`
  if (Array.isArray(value)) {
    if (value.length === 0) return `${key}: []`
    const items = value.map((item) => emitSeqItem(item, indent, pad))
    return [`${key}:`, ...items].join('\n')
  }
  const entries = Object.entries(value)
  if (entries.length === 0) return `${key}: {}`
  return [`${key}:`, emitBlockMap(value, indent + 2)].join('\n')
}

function emitSeqItem(item: FrontmatterValue, indent: number, pad: string): string {
  if (item === null) return `${pad}- null`
  if (typeof item === 'string') return `${pad}- ${emitScalar(item)}`
  if (typeof item === 'number' || typeof item === 'boolean') return `${pad}- ${String(item)}`
  if (Array.isArray(item)) {
    return [`${pad}-`, emitBlockValue(item, indent + 2)].join('\n')
  }
  const entries = Object.entries(item)
  if (entries.length === 0) return `${pad}- {}`
  const innerPad = ' '.repeat(indent + 2)
  const lines = entries.map(([k, v], idx) => {
    const body = emitEntry(k, v, indent + 2, innerPad)
    return (idx === 0 ? `${pad}- ` : innerPad) + body
  })
  return lines.join('\n')
}

function emitBlockValue(value: FrontmatterValue, indent: number): string {
  if (Array.isArray(value)) {
    const pad = ' '.repeat(indent)
    return value.map((item) => emitSeqItem(item, indent, pad)).join('\n')
  }
  return emitBlockMap(value as FrontmatterData, indent)
}
