/**
 * 装配（design-v3 §5 / harness-adapters §8 冲突策略）。
 *
 * | 情况 | 处理 |
 * | :--- | :--- |
 * | 目标文件不存在 | 写入 |
 * | 目标文件含 Prism marker | 覆盖 |
 * | 目标文件人写的（无 marker） | 不覆盖，写 `<name>.md.prism-new` 供对比，记入 skipped |
 * | --force | 一律覆盖（人写的也覆盖，不产生 .prism-new） |
 * | 目标目录不存在 | 自动创建（mkdir -p） |
 * | 目录不可写/创建失败 | 抛 InstallError（code='install_failed'，可读信息） |
 *
 * 安全：目标目录全部由参数传入，**绝不硬编码 ~/.zcode**；测试必须用临时目录。
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { renderZcodeRole } from './role/render.js'
import { renderZcodeTeam } from './team/render.js'
import { createTeamRegistry } from './registry.js'
import { ROLE_TEMPLATE_NAME_PLACEHOLDER, ROLE_TEMPLATE_MD } from './templates.js'
import type { InstallOptions, InstallResult, TeamDefinition } from './types.js'

const PRISM_MARKER = '<!-- generated by prism ('

/** 装配失败（目标不可写/创建失败等）。 */
export class InstallError extends Error {
  readonly code = 'install_failed'
  readonly path?: string

  constructor(message: string, path?: string) {
    super(`install_failed: ${message}${path ? ` (${path})` : ''}`)
    this.name = 'InstallError'
    this.path = path
  }
}

/** 装配角色到目标目录（`<targetDir>/<name>.md`）。 */
export async function installRoles(opts: InstallOptions): Promise<InstallResult> {
  const written: string[] = []
  const skipped: InstallResult['skipped'] = []
  ensureTargetDir(opts.targetDir)
  for (const role of opts.roles) {
    const path = join(opts.targetDir, `${role.name}.md`)
    const content = renderZcodeRole(role, opts.env)
    const outcome = resolveWrite(path, content, opts.force === true)
    if (outcome.action === 'written') written.push(path)
    else if (outcome.action === 'skipped') skipped.push({ path: outcome.path, reason: outcome.reason })
  }
  return { written, skipped }
}

export interface InstallTeamsOptions {
  /** ZCode agents 目录；团队定义写至 `<targetDir>/teams/<team_id>.md`。 */
  targetDir: string
  /** 显式团队受管目录（resolveDirs().teamsDir；提供时优先于 `<targetDir>/teams` 推导）。 */
  teamsDir?: string
  teams: TeamDefinition[]
  force?: boolean
}

/** 装配团队定义文件（供 `prism team install` / F13 端到端使用）。 */
export async function installTeamDefinitions(opts: InstallTeamsOptions): Promise<InstallResult> {
  const teamsDir = opts.teamsDir ?? join(opts.targetDir, 'teams')
  const written: string[] = []
  const skipped: InstallResult['skipped'] = []
  ensureTargetDir(teamsDir)
  for (const team of opts.teams) {
    const path = join(teamsDir, `${team.team_id}.md`)
    const content = renderZcodeTeam(team)
    const outcome = resolveWrite(path, content, opts.force === true)
    if (outcome.action === 'written') written.push(path)
    else if (outcome.action === 'skipped') skipped.push({ path: outcome.path, reason: outcome.reason })
  }
  return { written, skipped }
}

type WriteOutcome =
  | { action: 'written'; path: string }
  | { action: 'skipped'; path: string; reason: string }

/** 冲突判定（§5 表）。 */
function resolveWrite(path: string, content: string, force: boolean): WriteOutcome {
  if (existsSync(path)) {
    const existing = safeRead(path)
    if (existing === content) {
      // 幂等：内容一致不落盘（视为已就位，如实报告未写）
      return { action: 'skipped', path, reason: '内容一致，未重复写入' }
    }
    if (!force && !existing.includes(PRISM_MARKER)) {
      // 人写的文件：不覆盖，写 .prism-new 供对比
      const newPath = `${path}.prism-new`
      writeFile(newPath, content)
      return {
        action: 'skipped',
        path,
        reason: `目标文件由人编写（无 Prism marker），未覆盖；新版本已写入 ${newPath} 供对比`,
      }
    }
    // 含 Prism marker（Prism 产物）或 --force：覆盖
  }
  writeFile(path, content)
  return { action: 'written', path }
}

// ---------------------------------------------------------------------------
// 模板初始化与迁移（装配语义简化：install 从"复制装配"退化为"模板初始化"）
// ---------------------------------------------------------------------------

const KEBAB_CASE_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/

export interface InitRoleOptions {
  /** 新角色名（必须 kebab-case；ZCode 产物 = 文件名）。 */
  name: string
  /** 角色受管目录（resolveDirs().rolesDir；新模型下即宿主目录）。 */
  rolesDir: string
  /** 自定义模板（缺省用内置 ROLE_TEMPLATE_MD；`{{name}}` 会被替换）。 */
  template?: string
  /** 已存在时覆盖（缺省跳过，绝不覆盖人写文件）。 */
  force?: boolean
}

/**
 * `role init`：从模板创建角色到 roles_dir（直接住在宿主目录模型）。
 * 已存在 → skipped（除非 force）；name 非 kebab-case → InstallError。
 */
export async function initRole(opts: InitRoleOptions): Promise<InstallResult> {
  const name = opts.name.trim()
  if (!KEBAB_CASE_RE.test(name)) {
    throw new InstallError(`角色名必须是 kebab-case：${opts.name}（用于文件名 ${name}.md）`)
  }
  ensureTargetDir(opts.rolesDir)
  const path = join(opts.rolesDir, `${name}.md`)
  if (existsSync(path) && opts.force !== true) {
    // init 语义：文件已存在即跳过（人写/已初始化都不动；--force 才覆盖）
    return { written: [], skipped: [{ path, reason: '角色文件已存在（--force 覆盖）' }] }
  }
  const content = (opts.template ?? ROLE_TEMPLATE_MD).replaceAll(ROLE_TEMPLATE_NAME_PLACEHOLDER, name)
  writeFile(path, content)
  return { written: [path], skipped: [] }
}

export interface MigrateTeamsOptions {
  /** 旧源目录（如 <PRISM_HOME>/teams，目录式或扁平均可）。 */
  fromDir: string
  /** 团队受管目录（resolveDirs().teamsDir）。 */
  teamsDir: string
  /** 只迁移指定 team_id（缺省全量）。 */
  teamId?: string
  force?: boolean
}

/**
 * 团队定义一次性迁移（旧 Prism 源目录 → teamsDir）：`team install` 在团队文件
 * 尚在旧源目录时调用；冲突策略同 §5，天然幂等（已在 teamsDir 的不会重复写）。
 */
export async function migrateTeams(opts: MigrateTeamsOptions): Promise<InstallResult & { migrated: TeamDefinition[] }> {
  const { teams } = await createTeamRegistry().loadFromDirDetailed(opts.fromDir)
  const selected = opts.teamId === undefined ? teams : teams.filter((t) => t.team_id === opts.teamId)
  ensureTargetDir(opts.teamsDir)
  const written: string[] = []
  const skipped: InstallResult['skipped'] = []
  for (const team of selected) {
    const path = join(opts.teamsDir, `${team.team_id}.md`)
    const content = renderZcodeTeam(team)
    const outcome = resolveWrite(path, content, opts.force === true)
    if (outcome.action === 'written') written.push(path)
    else if (outcome.action === 'skipped') skipped.push({ path: outcome.path, reason: outcome.reason })
  }
  return { written, skipped, migrated: selected }
}

function ensureTargetDir(dir: string): void {
  try {
    mkdirSync(dir, { recursive: true })
  } catch (err) {
    throw new InstallError(`目标目录创建失败（不可写或被占用）：${err instanceof Error ? err.message : String(err)}`, dir)
  }
  if (!existsSync(dir)) {
    throw new InstallError('目标目录创建失败：路径不可用', dir)
  }
}

function safeRead(path: string): string {
  try {
    return readFileSync(path, 'utf8')
  } catch (err) {
    throw new InstallError(`目标文件不可读：${err instanceof Error ? err.message : String(err)}`, path)
  }
}

function writeFile(path: string, content: string): void {
  try {
    writeFileSync(path, content, 'utf8')
  } catch (err) {
    throw new InstallError(`目标文件不可写：${err instanceof Error ? err.message : String(err)}`, path)
  }
}
