/**
 * 角色渲染（RoleDefinition → ZCode 原生格式，harness-adapters §4.3）。
 *
 * 硬约束：
 * - frontmatter 只写 ZCode 白名单字段（name/description/color/model/thoughtLevel/injectAgentsMd），
 *   Prism 扩展（skills 白名单、知识绑定等）保留在正文，不污染 frontmatter；
 * - 含冒号/特殊字符的值必须加引号（emitScalar，harness §2.1）；
 * - 产物**末尾**追加 marker：`<!-- generated by prism (role: <name>) -->`（design-v3 §5 P12）。
 */

import { renderMarkdownFile, type FrontmatterData } from '../frontmatter.js'
import type { RoleDefinition } from '../types.js'

export interface RenderEnv {
  /** 环境注入的模型（覆盖角色自带值；两者皆无则省略该字段）。 */
  model?: string
  /** 环境注入的思考档位。 */
  thoughtLevel?: string
}

/** Prism 产物 marker（识别 + 冲突判定用）。 */
export function roleMarker(name: string): string {
  return `<!-- generated by prism (role: ${name}) -->`
}

/** 内容是否为 Prism 生成的角色产物。 */
export function hasPrismMarker(content: string): boolean {
  return content.includes('<!-- generated by prism (role: ')
}

/** Prism 叠加层正文节标题（harness §4.2：扩展一律放正文，不进 frontmatter）。 */
export const OVERLAY_SKILLS_HEADING = '## 能力（Skill 白名单）'
export const OVERLAY_KNOWLEDGE_HEADING = '## 知识绑定'

/** 渲染单个角色为 ZCode 角色文件内容。 */
export function renderZcodeRole(role: RoleDefinition, env: RenderEnv = {}): string {
  const fm: FrontmatterData = {
    name: role.name,
    description: role.description,
  }
  if (role.color !== undefined) fm.color = role.color
  const model = env.model ?? role.model
  if (model !== undefined && model !== '') fm.model = model
  const thoughtLevel = env.thoughtLevel ?? role.thoughtLevel
  if (thoughtLevel !== undefined && thoughtLevel !== '') fm.thoughtLevel = thoughtLevel
  if (role.injectAgentsMd !== undefined) fm.injectAgentsMd = role.injectAgentsMd

  const marker = roleMarker(role.name)
  const base = renderMarkdownFile(fm, composeBody(role))
  return `${base}\n${marker}\n`
}

/** 正文 + Prism 叠加层（能力白名单/知识绑定节；已存在则不重复注入，保证幂等）。 */
function composeBody(role: RoleDefinition): string {
  const base = role.body.trimEnd()
  const parts: string[] = [base]
  if (!base.includes(OVERLAY_SKILLS_HEADING) && role.skills.length > 0) {
    parts.push([OVERLAY_SKILLS_HEADING, ...role.skills.map((s) => `- ${s}`)].join('\n'))
  }
  const books = role.knowledge.books ?? []
  if (!base.includes(OVERLAY_KNOWLEDGE_HEADING) && (role.knowledge.layers.length > 0 || books.length > 0)) {
    const lines: string[] = [OVERLAY_KNOWLEDGE_HEADING]
    if (role.knowledge.layers.length > 0) lines.push(`- layers: ${role.knowledge.layers.join(', ')}`)
    if (books.length > 0) lines.push(`- books: ${books.join(', ')}`)
    parts.push(lines.join('\n'))
  }
  return parts.filter((p) => p !== '').join('\n\n')
}
