import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import { createMcpTools, handleRpcRequest, type JsonRpcResponse, type McpTool } from '../src/mcp/server.js'
import { CORE_DEV_TEAM_MD } from '../src/roles/templates.js'

const ZCODE_ROLE_MD = `---
name: dev-1
description: "开发角色：交付可运行增量，绝不扩大战场。"
color: blue
---

# 开发 1

## 核心契约
**交付可运行的增量，绝不扩大战场。**
`

const TEAM_MD = CORE_DEV_TEAM_MD.replace(/members:\n(?: {2}- role: .*\n {4}count: \d+\n)+/, 'members:\n  - role: dev-1\n    count: 2\n')

function rpc(
  id: number,
  method: string,
  params?: Record<string, unknown>,
): { jsonrpc: '2.0'; id: number; method: string; params?: Record<string, unknown> } {
  return { jsonrpc: '2.0', id, method, ...(params === undefined ? {} : { params }) }
}

function textOf(response: JsonRpcResponse | null): string {
  const content = (response?.result as { content?: Array<{ text?: string }> } | undefined)?.content
  return content?.[0]?.text ?? ''
}

describe('MCP 角色/团队工具（design-v3 §3.4 P6；stdio JSON-RPC 手写实现）', () => {
  let tmp: string
  let home: string
  let tools: McpTool[]

  beforeAll(async () => {
    tmp = await mkdtemp(join(tmpdir(), 'prism-mcp-people-'))
    home = join(tmp, 'home')
    // B8：MCP 数据源与 CLI 同源（resolveDirs）——prism.yaml 显式指向临时目录，避免回落真实宿主
    await mkdir(home, { recursive: true })
    await writeFile(
      join(home, 'prism.yaml'),
      `roles_dir: ${join(home, 'roles').replaceAll('\\', '/')}\nteams_dir: ${join(home, 'teams').replaceAll('\\', '/')}\n`,
      'utf-8',
    )
    await mkdir(join(home, 'roles', 'dev-1'), { recursive: true })
    await writeFile(join(home, 'roles', 'dev-1', 'AGENTS.md'), ZCODE_ROLE_MD, 'utf-8')
    await mkdir(join(home, 'teams', 'core-dev'), { recursive: true })
    await writeFile(join(home, 'teams', 'core-dev', 'AGENTS.md'), TEAM_MD, 'utf-8')
    tools = createMcpTools({ home, harnessRoot: join(tmp, 'zcode'), kbFactory: async () => { throw new Error('本测试不消费 kb') } })
  })

  afterAll(async () => {
    await rm(tmp, { recursive: true, force: true }).catch(() => {})
  })

  it('tools/list 含 4 个新工具（累计 30 个）', async () => {
    const response = await handleRpcRequest(rpc(1, 'tools/list'), tools)
    const names = ((response?.result as { tools: Array<{ name: string }> })?.tools ?? []).map((t) => t.name)
    expect(names).toEqual([
      'prism_kb_search',
      'prism_kb_get',
      'prism_kb_deposit',
      'prism_kb_convert',
      'prism_kb_import',
      'prism_kb_enrich',
      'prism_kb_graph',
      'prism_kb_tree',
      'prism_kb_stats',
      'prism_kb_catalog',
      'prism_kb_path',
      'prism_kb_remove',
      'prism_kb_conflicts',
      'prism_kb_resolve_conflict',
      'prism_graph_query',
      'prism_graph_status',
      'prism_graph_path',
      'prism_graph_explain',
      'prism_graph_affected',
      'prism_graph_summary',
      'prism_graph_god_nodes',
      'prism_role_list',
      'prism_role_get',
      'prism_context_pack',
      'prism_role_render',
      'prism_team_get',
      'prism_team_activate',
      'prism_task_register',
      'prism_task_report',
      'prism_task_status',
    ])
  })

  it('tools/call prism_role_list → 角色数组（数据源 <home>/roles/）', async () => {
    const response = await handleRpcRequest(rpc(2, 'tools/call', { name: 'prism_role_list', arguments: {} }), tools)
    expect(response?.result).toMatchObject({ isError: false })
    const value = JSON.parse(textOf(response)) as { count: number; roles: Array<{ name: string }> }
    expect(value.count).toBe(1)
    expect(value.roles[0].name).toBe('dev-1')
  })

  it('tools/call prism_role_render → ZCode 格式（marker + target 路径来自 harnessRoot 推导）', async () => {
    const response = await handleRpcRequest(
      rpc(3, 'tools/call', { name: 'prism_role_render', arguments: { name: 'dev-1', model: 'custom:x' } }),
      tools,
    )
    const value = JSON.parse(textOf(response)) as { name: string; target: string; content: string }
    expect(value.name).toBe('dev-1')
    expect(value.target).toContain(join('zcode', 'agents', 'dev-1.md'))
    expect(value.content).toContain('name: dev-1')
    expect(value.content).toContain('model: "custom:x"')
    expect(value.content).toContain('generated by prism (role: dev-1)')
  })

  it('tools/call prism_role_render 未知角色 → isError 文本', async () => {
    const response = await handleRpcRequest(rpc(4, 'tools/call', { name: 'prism_role_render', arguments: { name: 'ghost' } }), tools)
    expect(response?.result).toMatchObject({ isError: true })
    expect(textOf(response)).toContain('角色不存在: ghost')
  })

  it('tools/call prism_team_get → 团队定义；prism_team_activate → dispatch 状态', async () => {
    const get = await handleRpcRequest(rpc(5, 'tools/call', { name: 'prism_team_get', arguments: { team_id: 'core-dev' } }), tools)
    const team = JSON.parse(textOf(get)) as { team_id: string; rework_limit: number; workflow: unknown[] }
    expect(team.team_id).toBe('core-dev')
    expect(team.rework_limit).toBe(2)

    const activate = await handleRpcRequest(rpc(6, 'tools/call', { name: 'prism_team_activate', arguments: { team_id: 'core-dev' } }), tools)
    const activation = JSON.parse(textOf(activate)) as {
      team_id: string
      members: Array<{ role: string; installed: boolean; dispatch: string; definition?: { name: string } }>
      deposit: Record<string, unknown>
      arbitration: string[]
    }
    expect(activation.members[0]).toMatchObject({ role: 'dev-1', installed: false, dispatch: 'fallback' })
    expect(activation.members[0].definition?.name).toBe('dev-1')
    expect(activation.deposit.default_layer).toBe('project')
    expect(activation.arbitration).toEqual(['safety', 'requirement', 'quality', 'progress'])

    const missing = await handleRpcRequest(rpc(7, 'tools/call', { name: 'prism_team_activate', arguments: { team_id: 'nope' } }), tools)
    expect(missing?.result).toMatchObject({ isError: true })
    expect(textOf(missing)).toContain('团队不存在: nope')
  })
})
