import { existsSync } from 'node:fs'
import { mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import { createMcpTools, handleRpcRequest, type JsonRpcResponse, type McpTool } from '../src/mcp/server.js'
import { CORE_DEV_TEAM_MD } from '../src/roles/templates.js'

const ZCODE_ROLE_MD = `---
name: dev-1
description: "开发角色：交付可运行增量，绝不扩大战场。"
color: blue
---

# 开发 1

## 核心契约
**交付可运行的增量，绝不扩大战场。**
`

const TEAM_MD = CORE_DEV_TEAM_MD.replace(/members:\n(?: {2}- role: .*\n {4}count: \d+\n)+/, 'members:\n  - role: dev-1\n    count: 2\n')

function rpc(
  id: number,
  method: string,
  params?: Record<string, unknown>,
): { jsonrpc: '2.0'; id: number; method: string; params?: Record<string, unknown> } {
  return { jsonrpc: '2.0', id, method, ...(params === undefined ? {} : { params }) }
}

function textOf(response: JsonRpcResponse | null): string {
  const content = (response?.result as { content?: Array<{ text?: string }> } | undefined)?.content
  return content?.[0]?.text ?? ''
}

describe('MCP 角色/团队工具（design-v3 §3.4 P6；stdio JSON-RPC 手写实现）', () => {
  let tmp: string
  let home: string
  let tools: McpTool[]

  beforeAll(async () => {
    tmp = await mkdtemp(join(tmpdir(), 'prism-mcp-people-'))
    home = join(tmp, 'home')
    // B8：MCP 数据源与 CLI 同源（resolveDirs）——prism.yaml 显式指向临时目录，避免回落真实宿主
    await mkdir(home, { recursive: true })
    await writeFile(
      join(home, 'prism.yaml'),
      `roles_dir: ${join(home, 'roles').replaceAll('\\', '/')}\nteams_dir: ${join(home, 'teams').replaceAll('\\', '/')}\n`,
      'utf-8',
    )
    await mkdir(join(home, 'roles', 'dev-1'), { recursive: true })
    await writeFile(join(home, 'roles', 'dev-1', 'AGENTS.md'), ZCODE_ROLE_MD, 'utf-8')
    await mkdir(join(home, 'teams', 'core-dev'), { recursive: true })
    await writeFile(join(home, 'teams', 'core-dev', 'AGENTS.md'), TEAM_MD, 'utf-8')
    tools = createMcpTools({ home, harnessRoot: join(tmp, 'zcode'), kbFactory: async () => { throw new Error('本测试不消费 kb') } })
  })

  afterAll(async () => {
    await rm(tmp, { recursive: true, force: true }).catch(() => {})
  })

  it('tools/list 含新增工具（累计 43 个；v6 角色/团队补齐增删改，team_create → team_new）', async () => {
    const response = await handleRpcRequest(rpc(1, 'tools/list'), tools)
    const names = ((response?.result as { tools: Array<{ name: string }> })?.tools ?? []).map((t) => t.name)
    expect(names).toEqual([
      'prism_kb_search',
      'prism_kb_get',
      'prism_kb_versions',
      'prism_kb_book_structure',
      'prism_kb_deposit',
      'prism_kb_convert',
      'prism_kb_import',
      'prism_kb_enrich',
      'prism_kb_graph',
      'prism_kb_tree',
      'prism_kb_stats',
      'prism_kb_catalog',
      'prism_kb_path',
      'prism_kb_remove',
      'prism_kb_restore',
      'prism_kb_conflicts',
      'prism_kb_resolve_conflict',
      'prism_graph_query',
      'prism_graph_status',
      'prism_graph_path',
      'prism_graph_explain',
      'prism_graph_affected',
      'prism_graph_summary',
      'prism_graph_god_nodes',
      'prism_graph_merge',
      'prism_role_list',
      'prism_role_get',
      'prism_role_new',
      'prism_role_edit',
      'prism_role_rm',
      'prism_context_pack',
      'prism_skill_effective',
      'prism_role_render',
      'prism_team_list',
      'prism_team_get',
      'prism_team_activate',
      'prism_team_new',
      'prism_team_edit',
      'prism_team_rm',
      'prism_team_render',
      'prism_task_register',
      'prism_task_report',
      'prism_task_status',

    ])
  })

  it('tools/call prism_role_list → 角色数组（数据源 <home>/roles/）', async () => {
    const response = await handleRpcRequest(rpc(2, 'tools/call', { name: 'prism_role_list', arguments: {} }), tools)
    expect(response?.result).toMatchObject({ isError: false })
    const value = JSON.parse(textOf(response)) as { count: number; roles: Array<{ name: string }> }
    expect(value.count).toBe(1)
    expect(value.roles[0].name).toBe('dev-1')
  })

  it('tools/call prism_role_render → 宿主原生形态（marker + target = 真实落点 roles_dir）', async () => {
    const response = await handleRpcRequest(
      rpc(3, 'tools/call', { name: 'prism_role_render', arguments: { name: 'dev-1', model: 'custom:x' } }),
      tools,
    )
    const value = JSON.parse(textOf(response)) as { name: string; target: string; content: string }
    expect(value.name).toBe('dev-1')
    expect(value.target).toContain(join('home', 'roles', 'dev-1.md'))
    expect(value.content).toContain('name: dev-1')
    expect(value.content).toContain('model: "custom:x"')
    expect(value.content).toContain('generated by prism (role: dev-1)')
  })

  it('tools/call prism_role_render 未知角色 → isError 文本', async () => {
    const response = await handleRpcRequest(rpc(4, 'tools/call', { name: 'prism_role_render', arguments: { name: 'ghost' } }), tools)
    expect(response?.result).toMatchObject({ isError: true })
    expect(textOf(response)).toContain('角色不存在: ghost')
    // 角色侧错误文案给出的是目录式落点形态（双形态探测均支持）——勿随团队一起改
    expect(textOf(response)).toContain('<name>/AGENTS.md')
  })

  it('tools/call prism_team_get → 团队定义；prism_team_activate → dispatch 状态', async () => {
    const get = await handleRpcRequest(rpc(5, 'tools/call', { name: 'prism_team_get', arguments: { team_id: 'core-dev' } }), tools)
    const team = JSON.parse(textOf(get)) as { team_id: string; rework_limit: number; workflow: unknown[] }
    expect(team.team_id).toBe('core-dev')
    expect(team.rework_limit).toBe(2)

    const activate = await handleRpcRequest(rpc(6, 'tools/call', { name: 'prism_team_activate', arguments: { team_id: 'core-dev' } }), tools)
    const activation = JSON.parse(textOf(activate)) as {
      team_id: string
      members: Array<{ role: string; installed: boolean; dispatch: string; definition?: { name: string } }>
      deposit: Record<string, unknown>
      arbitration: string[]
    }
    expect(activation.members[0]).toMatchObject({ role: 'dev-1', installed: false, dispatch: 'fallback' })
    expect(activation.members[0].definition?.name).toBe('dev-1')
    expect(activation.deposit.default_layer).toBe('project')
    expect(activation.arbitration).toEqual(['safety', 'requirement', 'quality', 'progress'])

    const missing = await handleRpcRequest(rpc(7, 'tools/call', { name: 'prism_team_activate', arguments: { team_id: 'nope' } }), tools)
    expect(missing?.result).toMatchObject({ isError: true })
    expect(textOf(missing)).toContain('团队不存在: nope')
    // ui-spec-v4 §8-D5：文案报真实落点 <id>.md，目录式仅作兼容形态（旧文案只写 <id>/AGENTS.md → 引导错路径）
    expect(textOf(missing)).toContain('<id>.md')
    expect(textOf(missing)).toContain('兼容 <id>/AGENTS.md 双形态')
  })
})

/**
 * v6：角色 / 团队 MCP 工具的增删改（与 CLI `role|team new|edit|rm`、HTTP 写路由同一实现）。
 *
 * 断言重点是「**三入口同名同位**」这件事在 MCP 侧是否成立：
 * - 工具名 = `prism_role_new|edit|rm`、`prism_team_list|edit|rm|render`（`prism_team_create` 已更名）；
 * - 写路径的 `roles_dir` / `teams_dir` **必填**，缺参数一律 isError（绝不回落默认宿主目录）；
 * - `prism_team_edit` 改名册 → 工作流就地收窄并回 `workflow_pruned`（与 HTTP 同一实现）。
 */
describe('MCP 角色/团队写工具 v6（增删改三入口对齐）', () => {
  let tmp: string
  let home: string
  let writeRoles: string
  let writeTeams: string
  let tools: McpTool[]

  const call = async (name: string, args: Record<string, unknown>): Promise<JsonRpcResponse | null> =>
    await handleRpcRequest(rpc(99, 'tools/call', { name, arguments: args }), tools)

  beforeAll(async () => {
    tmp = await mkdtemp(join(tmpdir(), 'prism-mcp-people-v6-'))
    home = join(tmp, 'home')
    writeRoles = join(tmp, 'managed-roles')
    writeTeams = join(tmp, 'managed-teams')
    await mkdir(home, { recursive: true })
    await writeFile(
      join(home, 'prism.yaml'),
      `roles_dir: ${join(home, 'roles').replaceAll('\\', '/')}\nteams_dir: ${join(home, 'teams').replaceAll('\\', '/')}\n`,
      'utf-8',
    )
    // 角色库（供 team new 校验成员存在）
    await mkdir(join(home, 'roles', 'dev-1'), { recursive: true })
    await writeFile(join(home, 'roles', 'dev-1', 'AGENTS.md'), ZCODE_ROLE_MD, 'utf-8')
    await mkdir(join(home, 'roles', 'tester'), { recursive: true })
    await writeFile(join(home, 'roles', 'tester', 'AGENTS.md'), ZCODE_ROLE_MD.replace(/dev-1/g, 'tester'), 'utf-8')
    tools = createMcpTools({
      home,
      harnessRoot: join(tmp, 'zcode'),
      kbFactory: async () => {
        throw new Error('本测试不消费 kb')
      },
    })
  })

  afterAll(async () => {
    await rm(tmp, { recursive: true, force: true }).catch(() => {})
  })

  it('prism_role_new：缺 roles_dir → isError roles_dir_required（不落默认宿主目录）', async () => {
    const res = await call('prism_role_new', { name: 'mcp-role' })
    expect(res?.result).toMatchObject({ isError: true })
    expect(textOf(res)).toContain('roles_dir_required')
    expect(existsSync(join(home, 'roles', 'mcp-role.md'))).toBe(false)
  })

  it('prism_role_new：宿主原生形态落盘（frontmatter 不含 skills，扩展落正文）', async () => {
    const res = await call('prism_role_new', {
      name: 'mcp-role',
      description: 'MCP 建角色',
      skills: ['kb'],
      knowledge: { layers: ['global'] },
      roles_dir: writeRoles,
    })
    expect(res?.result).toMatchObject({ isError: false })
    const value = JSON.parse(textOf(res)) as { path: string; overwritten: boolean }
    expect(value.path.replaceAll('\\', '/')).toBe(join(writeRoles, 'mcp-role.md').replaceAll('\\', '/'))
    expect(value.overwritten).toBe(false)

    const md = await readFile(value.path, 'utf-8')
    const fm = md.slice(md.indexOf('---'), md.indexOf('---', 3))
    expect(fm).not.toContain('skills')
    expect(md).toContain('## 能力（Skill 白名单）')

    const dup = await call('prism_role_new', { name: 'mcp-role', roles_dir: writeRoles })
    expect(dup?.result).toMatchObject({ isError: true })
    expect(textOf(dup)).toContain('id_conflict')
  })

  it('prism_role_edit：字段补丁（改 skills）；目标不存在 → isError role_not_found', async () => {
    const res = await call('prism_role_edit', { name: 'mcp-role', skills: ['kb', 'graph'], roles_dir: writeRoles })
    expect(res?.result).toMatchObject({ isError: false })
    const md = await readFile(join(writeRoles, 'mcp-role.md'), 'utf-8')
    expect(md).toContain('- graph')

    const miss = await call('prism_role_edit', { name: 'ghost-role', description: 'x', roles_dir: writeRoles })
    expect(miss?.result).toMatchObject({ isError: true })
    expect(textOf(miss)).toContain('role_not_found')
  })

  it('prism_role_rm：硬删；再删 → isError role_not_found', async () => {
    const path = join(writeRoles, 'mcp-role.md')
    expect(existsSync(path)).toBe(true)
    const res = await call('prism_role_rm', { name: 'mcp-role', roles_dir: writeRoles })
    expect(res?.result).toMatchObject({ isError: false })
    expect((JSON.parse(textOf(res)) as { removed: string[] }).removed.length).toBe(1)
    expect(existsSync(path)).toBe(false)

    const again = await call('prism_role_rm', { name: 'mcp-role', roles_dir: writeRoles })
    expect(again?.result).toMatchObject({ isError: true })
    expect(textOf(again)).toContain('role_not_found')
  })

  it('prism_team_new / list / render：新建 → 列表可见 → 渲染宿主形态', async () => {
    const created = await call('prism_team_new', {
      team_id: 'mcp-team',
      name: 'MCP 队',
      members: [
        { role: 'dev-1', count: 1 },
        { role: 'tester', count: 1 },
      ],
      teams_dir: writeTeams,
    })
    expect(created?.result).toMatchObject({ isError: false })
    expect(existsSync(join(writeTeams, 'mcp-team.md'))).toBe(true)

    // `prism_team_list` 是**读**工具：读的是默认 teams_dir（home/teams），看不到显式写入的 writeTeams
    // —— 这正是「读跟随配置、写必须显式」的口径。把 home 指到 writeTeams 后才应看见它。
    const list = await call('prism_team_list', {})
    expect(list?.result).toMatchObject({ isError: false })
    expect((JSON.parse(textOf(list)) as { teams: Array<{ team_id: string }> }).teams).toEqual([])

    const readHome = await mkdtemp(join(tmpdir(), 'prism-mcp-people-v6-read-'))
    await writeFile(
      join(readHome, 'prism.yaml'),
      `roles_dir: ${join(home, 'roles').replaceAll('\\', '/')}\nteams_dir: ${writeTeams.replaceAll('\\', '/')}\n`,
      'utf-8',
    )
    const readTools = createMcpTools({
      home: readHome,
      harnessRoot: join(tmp, 'zcode'),
      kbFactory: async () => {
        throw new Error('本测试不消费 kb')
      },
    })
    try {
      const seen = await handleRpcRequest(rpc(98, 'tools/call', { name: 'prism_team_list', arguments: {} }), readTools)
      expect(seen?.result).toMatchObject({ isError: false })
      const seenValue = JSON.parse(textOf(seen)) as { teams: Array<{ team_id: string }> }
      expect(seenValue.teams.map((t) => t.team_id)).toContain('mcp-team')

      const render = await handleRpcRequest(
        rpc(97, 'tools/call', { name: 'prism_team_render', arguments: { team_id: 'mcp-team' } }),
        readTools,
      )
      expect(render?.result).toMatchObject({ isError: false })
      expect(textOf(render)).toContain('team_id: mcp-team')

      const ghost = await handleRpcRequest(
        rpc(96, 'tools/call', { name: 'prism_team_render', arguments: { team_id: 'no-such-team' } }),
        readTools,
      )
      expect(ghost?.result).toMatchObject({ isError: true })
    } finally {
      readTools.close?.()
      await rm(readHome, { recursive: true, force: true }).catch(() => {})
    }
  })

  it('prism_team_edit：改名册 → 工作流就地收窄（workflow_pruned）；prism_team_rm 硬删', async () => {
    const res = await call('prism_team_edit', {
      team_id: 'mcp-team',
      members: [{ role: 'dev-1', count: 2 }],
      teams_dir: writeTeams,
      roles_dir: join(home, 'roles'),
    })
    expect(res?.result).toMatchObject({ isError: false })
    const value = JSON.parse(textOf(res)) as { issues: Array<{ code: string }> }
    expect(value.issues.some((i) => i.code === 'workflow_pruned')).toBe(true)

    const md = await readFile(join(writeTeams, 'mcp-team.md'), 'utf-8')
    expect(md).not.toContain('- role: tester')

    const del = await call('prism_team_rm', { team_id: 'mcp-team', teams_dir: writeTeams })
    expect(del?.result).toMatchObject({ isError: false })
    expect(existsSync(join(writeTeams, 'mcp-team.md'))).toBe(false)
  })
})
