import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { parseRoleMarkdown } from '@prism/agents'

import { defaultContext, runCommand, type CommandContext } from '../src/argv.js'

/**
 * v6：`prism role new | edit | rm`——与 `prism team new | edit | rm` 严格对称，
 * 也与 `prism_role_new|edit|rm`（MCP）/ `POST|PATCH|DELETE /api/roles`（HTTP）同名同位。
 *
 * 形态口径（2026-09-12）：落盘是**宿主原生形态**——frontmatter 只含宿主白名单字段，
 * `skills` 白名单与知识绑定落正文的 `## 能力（Skill 白名单）` / `## 知识绑定` 两节。
 * 本文件只验 CLI 接线（flag → 输入）、输出文案、写守卫与 JSON 形状；
 * 「外科式补丁」的纯逻辑在 `@prism/agents` 的 role-write.test.ts 单测里。
 */

const ROLE_HAND = `---
name: hand-written
description: "手写角色：未知键与正文必须原样保留。"
color: cyan
customKey: keep-me
---

# 手写角色

## 核心第一原则
**人写的内容不该被命令重排。**
`

describe('prism role new（宿主原生形态）', () => {
  let home: string
  let lines: string[]
  let ctx: CommandContext
  const cleanup: string[] = []

  beforeEach(async () => {
    home = await mkdtemp(join(tmpdir(), 'prism-rolewrite-home-'))
    cleanup.push(home)
    // prism.yaml 覆盖 roles_dir/teams_dir → source='config'（守卫放行），全部落在临时目录（R5）
    const slash = home.replaceAll('\\', '/')
    await writeFile(join(home, 'prism.yaml'), `roles_dir: ${slash}/roles\nteams_dir: ${slash}/teams\n`, 'utf-8')
    await mkdir(join(home, 'roles'), { recursive: true })
    lines = []
    ctx = {
      ...defaultContext({
        stdout: (line) => lines.push(line),
        stderr: (line) => lines.push(`[stderr] ${line}`),
      }),
      home,
    }
  })

  afterEach(async () => {
    for (const dir of cleanup) {
      await rm(dir, { recursive: true, force: true }).catch(() => {})
    }
    cleanup.length = 0
  })

  it('只给名字：落 <roles_dir>/<name>.md（宿主原生形态）+ 提示描述待填', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'code-reviewer'])).toBe(0)
    const output = lines.join('\n')
    expect(output).toContain('目标 roles_dir:')
    expect(output).toContain('已创建')
    expect(output).toContain('宿主原生形态')
    expect(output).toContain('描述仍是占位 TODO')

    const path = join(home, 'roles', 'code-reviewer.md')
    expect(existsSync(path)).toBe(true)
    const content = await readFile(path, 'utf-8')
    // frontmatter 只含白名单字段；Prism 扩展在正文
    expect(content).toMatch(/^name: "?code-reviewer"?/m)
    expect(content).not.toMatch(/^skills:/m)
    expect(content).not.toMatch(/^knowledge:/m)
    expect(content).toContain('## 知识绑定')
    expect(content).toContain('<!-- generated by prism (role: code-reviewer) -->')
  })

  it('给了字段：写出的就是填好的定义（skills 落正文小节并可解析回）', async () => {
    expect(
      await runCommand(ctx, [
        'role', 'new', 'dev-x',
        '--description', '一句话职责：交付可运行增量。',
        '--skills', 'code_review,prism',
        '--layers', 'project',
        '--books', 'ps-pipeline',
        '--color', 'blue',
      ]),
    ).toBe(0)
    const content = await readFile(join(home, 'roles', 'dev-x.md'), 'utf-8')
    expect(content).toContain('## 能力（Skill 白名单）')
    expect(content).toContain('- code_review')
    expect(content).toContain('- layers: project')
    expect(content).toContain('- books: ps-pipeline')
    expect(content).toMatch(/^color: "?blue"?/m)

    const parsed = parseRoleMarkdown(content)
    expect(parsed.name).toBe('dev-x')
    expect(parsed.description).toBe('一句话职责：交付可运行增量。')
    expect(parsed.skills).toEqual(['code_review', 'prism'])
    expect(parsed.knowledge.layers).toEqual(['project'])
    expect(parsed.knowledge.books).toEqual(['ps-pipeline'])
  })

  it('已存在 → 未做任何改动，绝不覆盖（new 语义）；--force 覆盖', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x'])).toBe(0)
    const path = join(home, 'roles', 'dev-x.md')
    await writeFile(path, `${await readFile(path, 'utf-8')}\n<!-- 人工补充 -->\n`, 'utf-8')

    lines = []
    expect(await runCommand(ctx, ['role', 'new', 'dev-x'])).toBe(0)
    expect(lines.join('\n')).toContain('已存在，未做任何改动')
    expect(await readFile(path, 'utf-8')).toContain('<!-- 人工补充 -->')

    lines = []
    expect(await runCommand(ctx, ['role', 'new', 'dev-x', '--force', '--description', 'v2'])).toBe(0)
    expect(await readFile(path, 'utf-8')).toContain('v2')
    expect(await readFile(path, 'utf-8')).not.toContain('<!-- 人工补充 -->')
  })

  it('非 kebab-case 名 → role_name_invalid（rc 1），不落盘', async () => {
    lines = []
    expect(await runCommand(ctx, ['role', 'new', 'Dev_X'])).toBe(1)
    expect(lines.join('\n')).toContain('role_name_invalid')
    expect(existsSync(join(home, 'roles', 'Dev_X.md'))).toBe(false)
  })

  it('缺参数 → 用法提示（rc 1）', async () => {
    lines = []
    expect(await runCommand(ctx, ['role', 'new'])).toBe(1)
    expect(lines.join('\n')).toContain('用法: prism role new')
  })

  it('--json：rolesDir/name/written/skipped 结构化输出', async () => {
    lines = []
    expect(await runCommand(ctx, ['role', 'new', 'json-role', '--json'])).toBe(0)
    const out = JSON.parse(lines[lines.length - 1]) as {
      ok: boolean
      value: { rolesDir: string; name: string; written: string[]; skipped: unknown[] }
    }
    expect(out.ok).toBe(true)
    expect(out.value.name).toBe('json-role')
    expect(out.value.rolesDir.replaceAll('\\', '/')).toBe(join(home, 'roles').replaceAll('\\', '/'))
    expect(out.value.written).toEqual([join(home, 'roles', 'json-role.md')])
    expect(out.value.skipped).toEqual([])

    // 已存在 → skipped 结构（不静默）
    lines = []
    expect(await runCommand(ctx, ['role', 'new', 'json-role', '--json'])).toBe(0)
    const again = JSON.parse(lines[lines.length - 1]) as { value: { written: string[]; skipped: Array<{ reason: string }> } }
    expect(again.value.written).toEqual([])
    expect(again.value.skipped[0]?.reason).toContain('已存在')
  })

  it('写守卫：env 重定向的默认链（非显式）无 --yes → guard_required 拒绝', async () => {
    // env PRISM_HARNESS_ROOT 只重定向默认链、**不算显式指定** → 守卫保持生效（不会写真实宿主）
    const envRoot = await mkdtemp(join(tmpdir(), 'prism-rolewrite-env-'))
    cleanup.push(envRoot)
    const noConfigHome = await mkdtemp(join(tmpdir(), 'prism-rolewrite-noconf-'))
    cleanup.push(noConfigHome)
    const savedEnv = process.env['PRISM_HARNESS_ROOT']
    process.env['PRISM_HARNESS_ROOT'] = envRoot
    try {
      const guarded: CommandContext = { ...ctx, home: noConfigHome }
      lines = []
      expect(await runCommand(guarded, ['role', 'new', 'guarded'])).toBe(1)
      expect(lines.join('\n')).toContain('guard_required')
      expect(existsSync(join(envRoot, 'agents', 'guarded.md'))).toBe(false)

      // --yes 放行（仍写临时 envRoot，非真实宿主）
      lines = []
      expect(await runCommand(guarded, ['role', 'new', 'guarded', '--yes'])).toBe(0)
      expect(lines.join('\n')).toContain('--yes：确认写入默认宿主目录')
      expect(existsSync(join(envRoot, 'agents', 'guarded.md'))).toBe(true)
    } finally {
      if (savedEnv === undefined) delete process.env['PRISM_HARNESS_ROOT']
      else process.env['PRISM_HARNESS_ROOT'] = savedEnv
    }
  })
})

describe('prism role edit | rm（v6 增删改对齐）', () => {
  let home: string
  let lines: string[]
  let ctx: CommandContext
  const cleanup: string[] = []

  beforeEach(async () => {
    home = await mkdtemp(join(tmpdir(), 'prism-roleedit-home-'))
    cleanup.push(home)
    const slash = home.replaceAll('\\', '/')
    await writeFile(join(home, 'prism.yaml'), `roles_dir: ${slash}/roles\nteams_dir: ${slash}/teams\n`, 'utf-8')
    await mkdir(join(home, 'roles'), { recursive: true })
    lines = []
    ctx = {
      ...defaultContext({
        stdout: (line) => lines.push(line),
        stderr: (line) => lines.push(`[stderr] ${line}`),
      }),
      home,
    }
  })

  afterEach(async () => {
    for (const dir of cleanup) {
      await rm(dir, { recursive: true, force: true }).catch(() => {})
    }
    cleanup.length = 0
  })

  it('edit --description/--color：只改点名字段，正文与未知键原样保留', async () => {
    await writeFile(join(home, 'roles', 'hand-written.md'), ROLE_HAND, 'utf-8')
    lines = []
    expect(await runCommand(ctx, ['role', 'edit', 'hand-written', '--description', '改述', '--color', 'red'])).toBe(0)
    expect(lines.join('\n')).toContain('已更新')
    expect(lines.join('\n')).toContain('改动字段: description, color')

    const content = await readFile(join(home, 'roles', 'hand-written.md'), 'utf-8')
    // emitScalar 对非 ASCII 安全词加双引号（合法 YAML 标量）→ 断言容忍引号
    expect(content).toMatch(/^description: "?改述"?$/m)
    expect(content).toMatch(/^color: "?red"?/m)
    expect(content).toContain('customKey: keep-me') // 未知键未被抹掉
    expect(content).toContain('**人写的内容不该被命令重排。**') // 正文未被重排
    expect(content).not.toContain('generated by prism') // 人写文件不被塞 marker
  })

  it('edit --skills "": 清空白名单（正文 overlay 小节整体移除）', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x', '--skills', 'a,b'])).toBe(0)
    const path = join(home, 'roles', 'dev-x.md')
    expect(await readFile(path, 'utf-8')).toContain('## 能力（Skill 白名单）')

    lines = []
    expect(await runCommand(ctx, ['role', 'edit', 'dev-x', '--skills', ''])).toBe(0)
    expect(lines.join('\n')).toContain('改动字段: skills')
    const content = await readFile(path, 'utf-8')
    expect(content).not.toContain('## 能力（Skill 白名单）')
    expect(parseRoleMarkdown(content).skills).toEqual([])
  })

  it('edit --color "": 清除该 frontmatter 键（不留 color: "" 半残态）', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x', '--color', 'blue'])).toBe(0)
    const path = join(home, 'roles', 'dev-x.md')
    expect(await readFile(path, 'utf-8')).toMatch(/^color:/m)

    lines = []
    expect(await runCommand(ctx, ['role', 'edit', 'dev-x', '--color', ''])).toBe(0)
    const content = await readFile(path, 'utf-8')
    expect(content).not.toMatch(/^color:/m)
  })

  it('edit 未给任何字段 → bad_request（不静默成功）', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x'])).toBe(0)
    lines = []
    expect(await runCommand(ctx, ['role', 'edit', 'dev-x'])).toBe(1)
    expect(lines.join('\n')).toContain('未给出任何要修改的字段')
    expect(lines.join('\n')).toContain('用法: prism role edit')
  })

  it('edit 目标不存在 → role_not_found（只改不隐式新建）', async () => {
    lines = []
    expect(await runCommand(ctx, ['role', 'edit', 'nope', '--description', 'x'])).toBe(1)
    expect(lines.join('\n')).toContain('role_not_found')
    expect(existsSync(join(home, 'roles', 'nope.md'))).toBe(false)
  })

  it('rm：硬删文件本体；再次 rm → role_not_found', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x'])).toBe(0)
    const path = join(home, 'roles', 'dev-x.md')
    expect(existsSync(path)).toBe(true)

    lines = []
    expect(await runCommand(ctx, ['role', 'rm', 'dev-x'])).toBe(0)
    expect(lines.join('\n')).toContain('已删除')
    expect(existsSync(path)).toBe(false)

    lines = []
    expect(await runCommand(ctx, ['role', 'rm', 'dev-x'])).toBe(1)
    expect(lines.join('\n')).toContain('role_not_found')
  })

  it('rm 写守卫：默认宿主目录链无 --yes → guard_required 拒绝删除', async () => {
    const envRoot = await mkdtemp(join(tmpdir(), 'prism-rolerm-env-'))
    cleanup.push(envRoot)
    const noConfigHome = await mkdtemp(join(tmpdir(), 'prism-rolerm-noconf-'))
    cleanup.push(noConfigHome)
    const savedEnv = process.env['PRISM_HARNESS_ROOT']
    process.env['PRISM_HARNESS_ROOT'] = envRoot
    try {
      await mkdir(join(envRoot, 'agents'), { recursive: true })
      await writeFile(join(envRoot, 'agents', 'ghost.md'), '---\nname: ghost\ndescription: d\n---\n', 'utf-8')
      const guarded: CommandContext = { ...ctx, home: noConfigHome }

      lines = []
      expect(await runCommand(guarded, ['role', 'rm', 'ghost'])).toBe(1)
      expect(lines.join('\n')).toContain('guard_required')
      expect(existsSync(join(envRoot, 'agents', 'ghost.md'))).toBe(true)

      // --yes 放行（仍写临时 envRoot，非真实宿主）
      lines = []
      expect(await runCommand(guarded, ['role', 'rm', 'ghost', '--yes'])).toBe(0)
      expect(existsSync(join(envRoot, 'agents', 'ghost.md'))).toBe(false)
    } finally {
      if (savedEnv === undefined) delete process.env['PRISM_HARNESS_ROOT']
      else process.env['PRISM_HARNESS_ROOT'] = savedEnv
    }
  })

  it('list / render：render 的 target 是真实落点（rolesDir），非硬编码宿主根', async () => {
    expect(await runCommand(ctx, ['role', 'new', 'dev-x', '--description', '一句话。'])).toBe(0)

    lines = []
    expect(await runCommand(ctx, ['role', 'list'])).toBe(0)
    expect(lines.join('\n')).toContain('dev-x')
    expect(lines.join('\n')).toContain('共 1 个角色')

    lines = []
    expect(await runCommand(ctx, ['role', 'render', 'dev-x', '--json'])).toBe(0)
    const out = JSON.parse(lines[lines.length - 1]) as { value: { name: string; target: string; content: string } }
    expect(out.value.name).toBe('dev-x')
    // 真实落点 = prism.yaml 覆盖的 rolesDir（旧实现会固定拼 harnessRoot/agents，报出不存在的路径）
    expect(out.value.target.replaceAll('\\', '/')).toBe(join(home, 'roles', 'dev-x.md').replaceAll('\\', '/'))
    expect(out.value.content).toContain('name: dev-x')
  })
})

/**
 * v6.1 回归：`--source` 对**写命令**同样生效。
 *
 * 旧行为（实测确认的缺陷）：`role.ts` 里的 `rolesDir`（含 `--source` 覆盖）只被
 * list/show/validate/render 使用，`new`/`edit`/`rm` 硬用 `dirs.rolesDir` ——
 * 于是 `role rm dup --source <src>` 实际删掉的是**默认宿主目录**里那份（而该命令的用法串
 * 明写支持 `--source`），属不可逆误删。本块锁住「读写同源」这条契约。
 */
describe('prism role new|edit|rm --source（写命令与读命令同源）', () => {
  let home: string
  let src: string
  let lines: string[]
  let ctx: CommandContext
  const cleanup: string[] = []

  beforeEach(async () => {
    home = await mkdtemp(join(tmpdir(), 'prism-role-source-home-'))
    src = await mkdtemp(join(tmpdir(), 'prism-role-source-src-'))
    cleanup.push(home, src)
    await mkdir(join(home, 'roles'), { recursive: true })
    lines = []
    ctx = {
      ...defaultContext({
        stdout: (line) => lines.push(line),
        stderr: (line) => lines.push(`[stderr] ${line}`),
      }),
      home,
    }
  })

  afterEach(async () => {
    for (const dir of cleanup) {
      await rm(dir, { recursive: true, force: true }).catch(() => {})
    }
    cleanup.length = 0
  })

  it('new --source：落在 --source 指定目录，且不写默认 roles_dir（无需 --yes）', async () => {
    // 不带 --yes：`--source` 已显式指定目录，与 `--harness-root` 同口径解除写守卫
    expect(await runCommand(ctx, ['role', 'new', 'src-role', '--source', src])).toBe(0)
    expect(existsSync(join(src, 'src-role.md'))).toBe(true)
    expect(existsSync(join(home, 'roles', 'src-role.md'))).toBe(false)
    expect(lines.join('\n')).toContain('--source')
  })

  it('rm --source：删的是 --source 那份；默认目录的同名文件原封不动', async () => {
    const roleMd = '---\nname: dup\ndescription: d\n---\n'
    await writeFile(join(src, 'dup.md'), roleMd, 'utf-8')
    await writeFile(join(home, 'roles', 'dup.md'), roleMd, 'utf-8')

    expect(await runCommand(ctx, ['role', 'rm', 'dup', '--source', src])).toBe(0)
    expect(existsSync(join(src, 'dup.md'))).toBe(false) // 目标被删
    expect(existsSync(join(home, 'roles', 'dup.md'))).toBe(true) // 旧实现删的是这里
  })

  it('edit --source：改的是 --source 那份', async () => {
    const roleMd = '---\nname: e2\ndescription: 原述\n---\n'
    await writeFile(join(src, 'e2.md'), roleMd, 'utf-8')
    await writeFile(join(home, 'roles', 'e2.md'), roleMd, 'utf-8')

    expect(await runCommand(ctx, ['role', 'edit', 'e2', '--source', src, '--description', '改述'])).toBe(0)
    expect(await readFile(join(src, 'e2.md'), 'utf-8')).toContain('改述')
    expect(await readFile(join(home, 'roles', 'e2.md'), 'utf-8')).toContain('原述')
  })
})
