import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { defaultContext, runCommand, type CommandContext } from '../src/argv.js'

const ROLE_DEV1 = `---
name: dev-1
description: "开发角色：交付可运行增量。"
color: blue
---

# 开发 1

## 核心契约
**交付可运行的增量。**
`

const ROLE_TESTER = `---
name: tester
description: "测试角色：没证据不放行。"
color: green
---

# 测试

## 核心契约
**没证据不放行。**
`

/** F-C1：`prism team init`（脚手架 → 自动校验 → 写守卫 → 落盘）。 */
describe('prism team init（F-C1）', () => {
  let home: string
  let harnessRoot: string
  let lines: string[]
  let ctx: CommandContext
  const cleanup: string[] = []
  const savedEnv = process.env['PRISM_HARNESS_ROOT']

  beforeEach(async () => {
    home = await mkdtemp(join(tmpdir(), 'prism-teaminit-home-'))
    harnessRoot = await mkdtemp(join(tmpdir(), 'prism-teaminit-root-'))
    cleanup.push(home, harnessRoot)
    // prism.yaml 覆盖 roles_dir/teams_dir → source='config'（守卫放行），全部落在临时目录（R5）
    await writeFile(
      join(home, 'prism.yaml'),
      `roles_dir: ${home.replaceAll('\\', '/')}/roles\nteams_dir: ${home.replaceAll('\\', '/')}/teams\n`,
      'utf-8',
    )
    await mkdir(join(home, 'roles'), { recursive: true })
    await writeFile(join(home, 'roles', 'dev-1.md'), ROLE_DEV1, 'utf-8')
    await writeFile(join(home, 'roles', 'tester.md'), ROLE_TESTER, 'utf-8')
    lines = []
    ctx = {
      ...defaultContext({
        stdout: (line) => lines.push(line),
        stderr: (line) => lines.push(`[stderr] ${line}`),
      }),
      home,
    }
  })

  afterEach(async () => {
    if (savedEnv === undefined) delete process.env['PRISM_HARNESS_ROOT']
    else process.env['PRISM_HARNESS_ROOT'] = savedEnv
    for (const dir of cleanup) {
      await rm(dir, { recursive: true, force: true }).catch(() => {})
    }
    cleanup.length = 0
  })

  it('最小模板建队：落 <teams_dir>/<id>.md（扁平）+ 内容可被 loadTeam/validate 读回', async () => {
    expect(
      await runCommand(ctx, ['team', 'init', 'demo-team', '--name', '演示团队', '--description', '演示：冒烟用。']),
    ).toBe(0)
    const output = lines.join('\n')
    expect(output).toContain('已创建')
    const path = join(home, 'teams', 'demo-team.md')
    expect(existsSync(path)).toBe(true)
    const content = await readFile(path, 'utf-8')
    expect(content).toContain('team_id: demo-team')
    // emitScalar 对非 ASCII 安全词加双引号（合法 YAML 标量，parse 回原文）
    expect(content).toMatch(/name: "?演示团队"?/)
    expect(content).toContain('<!-- generated by prism (team: demo-team) -->')

    // 闭环：team show / team validate 都能读到（registry 双形态）
    lines = []
    expect(await runCommand(ctx, ['team', 'show', 'demo-team', '--json'])).toBe(0)
    const shown = JSON.parse(lines[lines.length - 1]) as {
      value: { team_id: string; name: string; members: Array<{ role: string; count: number }> }
    }
    expect(shown.value.team_id).toBe('demo-team')
    expect(shown.value.name).toBe('演示团队')
    expect(shown.value.members).toEqual([
      { role: 'dev-1', count: 1 },
      { role: 'tester', count: 1 },
    ])

    lines = []
    expect(await runCommand(ctx, ['team', 'validate', 'demo-team'])).toBe(0)
    expect(lines.join('\n')).toContain('通过')
  })

  it('已存在 → skipped，绝不覆盖（init 语义）', async () => {
    expect(await runCommand(ctx, ['team', 'init', 'demo-team'])).toBe(0)
    const path = join(home, 'teams', 'demo-team.md')
    // 人工改动（模拟人写内容）后重跑：必须原样保留
    await writeFile(path, `${await readFile(path, 'utf-8')}\n<!-- 人工补充 -->\n`, 'utf-8')
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'demo-team'])).toBe(0)
    expect(lines.join('\n')).toContain('跳过')
    expect(await readFile(path, 'utf-8')).toContain('<!-- 人工补充 -->')
  })

  it('--members <role[:n],...>：count 缺省=1；名册收窄自动裁剪工作流', async () => {
    expect(await runCommand(ctx, ['team', 'init', 'solo', '--members', 'dev-1:2'])).toBe(0)
    lines = []
    expect(await runCommand(ctx, ['team', 'show', 'solo', '--json'])).toBe(0)
    const shown = JSON.parse(lines[lines.length - 1]) as {
      value: { members: Array<{ role: string; count: number }>; workflow: Array<{ stage: string }> }
    }
    expect(shown.value.members).toEqual([{ role: 'dev-1', count: 2 }])
    // 工作流里 tester 阶段被剔除（否则生成即 workflow_role_unknown）
    expect(shown.value.workflow.map((s) => s.stage)).toEqual(['开发', '收口'])
  })

  it('成员角色不在角色库 → validateTeam error → 不落盘（rc 1）', async () => {
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'ghost-team', '--members', 'ghost-role'])).toBe(1)
    expect(lines.join('\n')).toContain('member_role_unknown')
    expect(lines.join('\n')).toContain('未落盘')
    expect(existsSync(join(home, 'teams', 'ghost-team.md'))).toBe(false)
  })

  it('--members 语法非法 → members_invalid，不落盘', async () => {
    for (const bad of ['dev-1:0', ':2', 'dev-1:2:3']) {
      lines = []
      expect(await runCommand(ctx, ['team', 'init', 'bad-team', '--members', bad])).toBe(1)
      expect(lines.join('\n')).toContain('members_invalid')
    }
    expect(existsSync(join(home, 'teams', 'bad-team.md'))).toBe(false)
  })

  it('team_id 非 kebab-case → team_id_invalid', async () => {
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'Demo_Team'])).toBe(1)
    expect(lines.join('\n')).toContain('team_id_invalid')
    expect(existsSync(join(home, 'teams', 'Demo_Team.md'))).toBe(false)
  })

  it('--from 克隆：成员/技能/沉淀策略继承，id 与名换新', async () => {
    expect(
      await runCommand(ctx, [
        'team', 'init', 'base-team', '--name', '基座团队',
        '--members', 'dev-1:1,tester:1',
      ]),
    ).toBe(0)
    lines = []
    expect(
      await runCommand(ctx, ['team', 'init', 'child-team', '--from', 'base-team', '--name', '子团队']),
    ).toBe(0)
    lines = []
    expect(await runCommand(ctx, ['team', 'show', 'child-team', '--json'])).toBe(0)
    const shown = JSON.parse(lines[lines.length - 1]) as {
      value: { team_id: string; name: string; members: Array<{ role: string }>; deposit: { default_type: string } }
    }
    expect(shown.value.team_id).toBe('child-team')
    expect(shown.value.name).toBe('子团队')
    expect(shown.value.members.map((m) => m.role)).toEqual(['dev-1', 'tester'])
    expect(shown.value.deposit.default_type).toBe('pitfall') // 继承源
  })

  it('--from 不存在 → not_found；--template 非法 → bad_request', async () => {
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'x-team', '--from', 'nope'])).toBe(1)
    expect(lines.join('\n')).toContain('not_found')

    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'x-team', '--template', 'nope'])).toBe(1)
    expect(lines.join('\n')).toContain('bad_request')
  })

  it('缺参数 → 用法提示（rc 1）', async () => {
    lines = []
    expect(await runCommand(ctx, ['team', 'init'])).toBe(1)
    expect(lines.join('\n')).toContain('用法: prism team init')
  })

  it('写守卫：env 重定向的默认链（非显式）无 --yes → guard_required 拒绝', async () => {
    // env PRISM_HARNESS_ROOT 只重定向默认链、**不算显式指定** → 守卫保持生效（不会写真实宿主）
    const envRoot = await mkdtemp(join(tmpdir(), 'prism-teaminit-env-'))
    cleanup.push(envRoot)
    await mkdir(join(envRoot, 'agents'), { recursive: true })
    await writeFile(join(envRoot, 'agents', 'dev-1.md'), ROLE_DEV1, 'utf-8')
    await writeFile(join(envRoot, 'agents', 'tester.md'), ROLE_TESTER, 'utf-8')
    const noConfigHome = await mkdtemp(join(tmpdir(), 'prism-teaminit-noconf-'))
    cleanup.push(noConfigHome)
    process.env['PRISM_HARNESS_ROOT'] = envRoot

    lines = []
    const guarded: CommandContext = { ...ctx, home: noConfigHome }
    expect(await runCommand(guarded, ['team', 'init', 'guarded-team'])).toBe(1)
    expect(lines.join('\n')).toContain('guard_required')
    expect(existsSync(join(envRoot, 'teams', 'guarded-team.md'))).toBe(false)

    // --yes 放行（仍写临时 envRoot，非真实宿主）
    lines = []
    expect(await runCommand(guarded, ['team', 'init', 'guarded-team', '--yes'])).toBe(0)
    expect(existsSync(join(envRoot, 'teams', 'guarded-team.md'))).toBe(true)
  })

  it('写守卫：--harness-root <tmp> 显式指定 → 直接放行（无需 --yes）', async () => {
    const explicitRoot = await mkdtemp(join(tmpdir(), 'prism-teaminit-explicit-'))
    cleanup.push(explicitRoot)
    await mkdir(join(explicitRoot, 'agents'), { recursive: true })
    await writeFile(join(explicitRoot, 'agents', 'dev-1.md'), ROLE_DEV1, 'utf-8')
    await writeFile(join(explicitRoot, 'agents', 'tester.md'), ROLE_TESTER, 'utf-8')
    const noConfigHome = await mkdtemp(join(tmpdir(), 'prism-teaminit-noconf2-'))
    cleanup.push(noConfigHome)
    lines = []
    const explicit: CommandContext = { ...ctx, home: noConfigHome }
    expect(
      await runCommand(explicit, ['team', 'init', 'explicit-team', '--harness-root', explicitRoot]),
    ).toBe(0)
    expect(existsSync(join(explicitRoot, 'teams', 'explicit-team.md'))).toBe(true)
  })

  it('--json：written/skipped/issues 结构化输出', async () => {
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'json-team', '--json'])).toBe(0)
    const out = JSON.parse(lines[lines.length - 1]) as {
      ok: boolean
      value: { teamId: string; written: string[]; skipped: unknown[]; issues: Array<{ level: string }> }
    }
    expect(out.ok).toBe(true)
    expect(out.value.teamId).toBe('json-team')
    expect(out.value.written).toEqual([join(home, 'teams', 'json-team.md')])
    expect(out.value.issues.filter((i) => i.level === 'error')).toEqual([])

    // 已存在 → skipped 结构
    lines = []
    expect(await runCommand(ctx, ['team', 'init', 'json-team', '--json'])).toBe(0)
    const again = JSON.parse(lines[lines.length - 1]) as { value: { skipped: Array<{ reason: string }> } }
    expect(again.value.skipped[0]?.reason).toContain('已存在')
  })
})
