/**
 * WorkBuddy 宿主适配器 —— Prism **运行期插件**（不改 Prism 源码、不需重新编译）。
 *
 * 安装：
 *   1. 复制本目录到 `<PRISM_HOME>/harnesses/workbuddy/`
 *   2. `<PRISM_HOME>/prism.yaml` 写 `harness: workbuddy`（或临时 `PRISM_HARNESS=workbuddy`）
 *   3. `prism harness list` 应看到 `workbuddy (external)`
 *
 * ## 自述的宿主约定（哪些核实过，哪些没有）
 *
 * | 关注点 | 约定 | 状态 |
 * | :--- | :--- | :--- |
 * | Skill | `<root>/skills/<name>/SKILL.md` | ✅ 实测存在（本机 `~/.workbuddy/skills/dsh-stack-recovery`） |
 * | MCP 注册 | `<root>/mcp.json`，**平铺** `{ mcpServers: { prism: { command, args, env } } }` | ✅ 官方自定义连接器口径 |
 * | 项目指令 | `<repo>/AGENTS.md` | ✅ 仓库根 AGENTS.md 被读取 |
 * | 角色文件 | `<root>/agents/<name>.md`（通用 markdown + 直引 frontmatter） | ⚠️ **未核实** |
 *
 * **关于「未核实」**：WorkBuddy 没有公开的「角色目录」约定（它的专家/角色走插件市场，
 * 不是扫描某个 agents/ 目录）。因此 `team install` 落在 `<root>/agents/` 的文件是
 * **惰性产物**——Prism 侧流程完整、可审计、可回滚，但**不宣称 WorkBuddy 会加载它们**。
 * 本适配器保证的是 **Skill + MCP 两条真实接入路径**。
 *
 * ## 实现约束
 *
 * 本文件由 Prism 用**动态 import** 加载，解析基准是**插件自身所在目录**，不在 Prism
 * 的 node_modules 链上——故**必须自包含**，不得 `import '@prism/*'`，只用 node 内置模块。
 */

import { existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

export const WORKBUDDY_ADAPTER_ID = 'workbuddy'

/** 默认 WorkBuddy 根（仅探测/展示缺省；写操作目标一律由调用方显式传入）。 */
export const DEFAULT_WORKBUDDY_DIR = join(homedir(), '.workbuddy')

/** Prism 产物 marker（与 `@prism/agents` 的 install 冲突策略同源，才能被识别为「可覆盖」）。 */
const MARKER = '<!-- generated by prism ('
const roleMarker = (name) => `${MARKER}role: ${name}) -->`
const teamMarker = (id) => `${MARKER}team: ${id}) -->`

/** YAML 标量安全输出：含冒号/井号/引号/首尾空格时用 JSON 双引号（JSON 字符串是合法 YAML 标量）。 */
function yamlScalar(value) {
  const s = String(value)
  if (s === '') return '""'
  const risky = /[:#'"\\\n]/.test(s) || s !== s.trim() || /^[-?*&!|>%@`[]/.test(s)
  return risky ? JSON.stringify(s) : s
}

/** frontmatter + 正文 → 文件内容（与 Prism 侧渲染形态一致：`---` 头 + 正文 + marker 尾）。 */
function compose(fields, body, marker) {
  const head = Object.entries(fields)
    .map(([k, v]) => `${k}: ${yamlScalar(v)}`)
    .join('\n')
  const trimmed = String(body ?? '').trimEnd()
  return `---\n${head}\n---\n\n${trimmed}\n\n${marker}\n`
}

/** 极简 frontmatter 解析（只认标量键值；够角色/团队文件往返）。 */
function parseFrontmatter(raw) {
  const text = String(raw ?? '').replace(/^\uFEFF/, '')
  if (!text.startsWith('---')) return { fields: {}, body: text }
  const end = text.indexOf('\n---', 3)
  if (end === -1) return { fields: {}, body: text }
  const block = text.slice(text.indexOf('\n', 3) + 1, end)
  const body = text.slice(text.indexOf('\n', end + 1) + 1)
  const fields = {}
  for (const line of block.split(/\r?\n/)) {
    const m = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(line)
    if (m === null) continue
    let value = m[2].trim()
    if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
      try {
        value = JSON.parse(value)
      } catch {
        value = value.slice(1, -1)
      }
    }
    fields[m[1]] = value
  }
  return { fields, body }
}

/** 去掉 Prism marker 尾注释，得到纯正文。 */
function stripMarkerTail(body) {
  return String(body ?? '')
    .split(/\r?\n/)
    .filter((line) => !line.includes(MARKER))
    .join('\n')
    .trim()
}

/** 团队工作流表（与 ZCode 适配器同款列，便于人读）。 */
function workflowTable(team) {
  const rows = team.workflow
    .map(
      (s) =>
        `| ${s.order} | ${s.stage} | ${s.roles.join(' + ')} | ${s.mode} | ${s.input} | ${s.output} | ${s.done} | ${s.reflow} |`,
    )
    .join('\n')
  return [
    '| # | 阶段 | 负责角色 | 串/并行 | 输入 | 输出 | 完成判定 | 回流路径 |',
    '| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |',
    rows,
  ].join('\n')
}

/** 创建 WorkBuddy 适配器（Prism 注入 root / repoDir）。 */
export default function createAdapter(opts = {}) {
  const root = opts.root ?? process.env['WORKBUDDY_DIR'] ?? DEFAULT_WORKBUDDY_DIR
  const agentsDir = join(root, 'agents')
  const teamsDir = join(root, 'teams')
  const skillsDir = join(root, 'skills')

  return {
    id: WORKBUDDY_ADAPTER_ID,
    displayName: 'WorkBuddy',
    defaultRoot: root,

    async detect() {
      if (!existsSync(root)) {
        return { installed: false, reason: `WorkBuddy 配置目录不存在：${root}` }
      }
      return { installed: true, configDir: root }
    },

    agent: {
      globalDir: agentsDir,
      projectDir: opts.repoDir ? join(opts.repoDir, '.workbuddy', 'agents') : '<repo>/.workbuddy/agents',
      filePattern: '<role>.md',
      teamDir: teamsDir,
      frontmatterFields: ['name', 'description'],
      bodyConvention: '## 核心契约',
      activation: 'session-start',
      nameMustMatchFile: true,
    },

    // WorkBuddy 无「按名称派发子 agent」的公开机制 → null（走 MCP 工具 + 上下文注入）
    dispatch: null,
    // WorkBuddy 的角色文件不支持声明模型（模型在宿主侧选） → null
    model: null,

    skill: {
      nativeDir: skillsDir,
      // WorkBuddy 的 Skill 目录就是 ~/.workbuddy/skills，没有第二生态目录
      ecosystemDir: null,
      format: 'SKILL.md',
      supported: true,
    },

    instructions: {
      file: 'AGENTS.md',
      projectFile: opts.repoDir ? join(opts.repoDir, 'AGENTS.md') : '<repo>/AGENTS.md',
    },

    // MCP 注册：<root>/mcp.json，**平铺** mcpServers（注意不是 ZCode 的 mcp.servers 嵌套）
    mcp: {
      configFile: join(root, 'mcp.json'),
      format: 'mcpServers-json',
      serverName: 'prism',
    },

    renderRole(role) {
      const fields = { name: role.name, description: role.description }
      const parts = [String(role.body ?? '').trimEnd()]
      if (role.skills !== undefined && role.skills.length > 0) {
        parts.push(['## 能力（Skill 白名单）', ...role.skills.map((s) => `- ${s}`)].join('\n'))
      }
      return {
        path: join(agentsDir, `${role.name}.md`),
        content: compose(fields, parts.filter((p) => p !== '').join('\n\n'), roleMarker(role.name)),
        format: 'markdown',
        writePolicy: 'overwrite',
        marker: roleMarker(role.name),
      }
    },

    renderTeamDefinition(team) {
      return {
        path: join(teamsDir, `${team.team_id}.md`),
        content: compose(
          { name: team.name, description: team.description },
          [
            `# 团队：${team.name}（${team.team_id}）`,
            '',
            '## 工作流',
            '',
            workflowTable(team),
            '',
            `仲裁链：${team.arbitration.join(' > ') || '（未定义）'}`,
            `返工上限：${team.rework_limit} 轮`,
          ].join('\n'),
          teamMarker(team.team_id),
        ),
        format: 'markdown',
        writePolicy: 'overwrite',
        marker: teamMarker(team.team_id),
      }
    },

    parseRole(content, filename) {
      const { fields, body } = parseFrontmatter(content)
      const clean = stripMarkerTail(body)
      return {
        name: fields['name'] ?? '',
        description: fields['description'] ?? '',
        skills: [],
        knowledge: { layers: ['global', 'project'], books: [] },
        principle: '',
        body: clean,
        ...(fields['color'] !== undefined ? { color: fields['color'] } : {}),
        sourcePath: filename,
      }
    },

    /** 团队约定注入：标记块合并进 `<repo>/AGENTS.md`（无 repoDir 则不注入）。 */
    renderTeamInstructions(team) {
      if (opts.repoDir === undefined) return null
      const start = `<!-- prism:team:${team.team_id}:start -->`
      const end = `<!-- prism:team:${team.team_id}:end -->`
      const content = [
        start,
        `# 团队约定：${team.name}（${team.team_id}）`,
        '',
        team.description,
        '',
        '## 工作流',
        '',
        workflowTable(team),
        '',
        `仲裁链：${team.arbitration.join(' > ') || '（未定义）'}`,
        `返工上限：${team.rework_limit} 轮`,
        end,
        '',
      ].join('\n')
      return {
        path: join(opts.repoDir, 'AGENTS.md'),
        content,
        format: 'markdown',
        writePolicy: 'merge',
        marker: start,
      }
    },
  }
}

export { createAdapter }
