/**
 * Prism 产物 marker（design-v3 §5 P12）：
 * - 角色/ZCode 产物：追加在文件末尾（`<!-- generated by prism (role: <name>) -->`，agents 包/serever roles 侧同一前缀）
 * - SKILL.md：marker 写在其自身 frontmatter 之后的独立注释行（不进正文语义）
 * 统一检测前缀 `<!-- generated by prism (`，据此区分「Prism 装的（可覆盖）」与「人写的（不覆盖）」。
 */
export const PRISM_MARKER_PREFIX = '<!-- generated by prism ('

/** SKILL.md 的 Prism marker（独立注释行）。 */
export function prismSkillMarker(name: string): string {
  return `${PRISM_MARKER_PREFIX}skill: ${name}) -->`
}

/** 判断文件内容是否为 Prism 产物（可安全覆盖）。 */
export function hasPrismMarker(content: string): boolean {
  return content.includes(PRISM_MARKER_PREFIX)
}
