/**
 * 团队定义渲染（TeamDefinition → ZCode 团队文件，供装配写入 `<targetDir>/teams/`）。
 *
 * 引号约束与角色渲染一致（emitScalar）；marker 变体：`<!-- generated by prism (team: <id>) -->`。
 */

import { renderMarkdownFile, type FrontmatterData, type FrontmatterValue } from '../frontmatter.js'
import type { TeamDefinition } from '../types.js'

export function teamMarker(teamId: string): string {
  return `<!-- generated by prism (team: ${teamId}) -->`
}

/** 内容是否为 Prism 生成的团队产物。 */
export function hasTeamMarker(content: string): boolean {
  return content.includes('<!-- generated by prism (team: ')
}

/** 渲染单个团队定义为 ZCode 团队文件内容（可被 renderZcodeTeam → parse 往返）。 */
export function renderZcodeTeam(team: TeamDefinition): string {
  const fm: FrontmatterData = {
    team_id: team.team_id,
    name: team.name,
    description: team.description,
    default: team.default,
  }
  if (team.extends !== undefined && team.extends !== null) fm.extends = team.extends
  fm.members = team.members.map((m) => ({ role: m.role, count: m.count }))
  fm.skills = [...team.skills]
  fm.knowledge = { layers: [...team.knowledge.layers], ...(team.knowledge.books ? { books: [...team.knowledge.books] } : {}) }
  const deposit: FrontmatterData = {
    enabled: team.deposit.enabled,
    default_layer: team.deposit.default_layer,
    default_type: team.deposit.default_type,
    priority: team.deposit.priority,
    require_note: team.deposit.require_note,
  }
  if (team.deposit.rules !== undefined) {
    // match/set 内容为扁平原始值（校验器保证为对象），此处结构化透传
    deposit.rules = team.deposit.rules.map((r) => ({
      match: { ...r.match } as Record<string, FrontmatterValue>,
      set: { ...r.set } as Record<string, FrontmatterValue>,
    }))
  }
  fm.deposit = deposit
  fm.arbitration = [...team.arbitration]
  fm.rework_limit = team.rework_limit

  const marker = teamMarker(team.team_id)
  const base = renderMarkdownFile(fm, team.body.trimEnd())
  return `${base}\n${marker}\n`
}
