/**
 * 团队写盘（`prism team edit | rm`）。
 *
 * 分工：`team new` 的脚手架渲染在 `team/init.ts`（`renderTeamScaffold`，只渲染不落盘）；
 * 本文件负责**改**与**删**——与 `role/write.ts` 对称。
 *
 * `edit` 是**外科式补丁**：`patchTeamRaw` 只动点名的那几处：
 * - `members` 变更 → 复用 `narrowWorkflow` + `renderWorkflowTable` + `replaceWorkflowSection`
 *   就地收窄 `## 工作流` 表（与 `team new --members` 同一套实现，绝不造第二个裁剪器）；
 * - 其余 frontmatter 键（name/description/skills/knowledge/deposit/arbitration/rework_limit）就地覆盖；
 * - 正文其余小节与未知 frontmatter 键原样保留。
 *
 * `rm` 只删团队文件本体（扁平 `<id>.md` 与兼容形态 `<id>/AGENTS.md` 都认）；是否放行由调用方的
 * 写守卫决定（默认宿主目录需 `--yes`）。
 *
 * 安全：目标目录由参数传入，**绝不硬编码宿主根**；测试必须用临时目录。
 */

import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { renderMarkdownFile, splitFrontmatter, type FrontmatterData } from '../frontmatter.js'
import type { DepositPolicy, KnowledgeBinding, TeamMember, ValidationIssue } from '../types.js'
import { narrowWorkflow, renderWorkflowTable, replaceWorkflowSection } from './init.js'
import { parseWorkflowTable } from './parse.js'
import { stripInstanceMarker } from './validate.js'

/** 团队写盘失败（id 非法 / 目录不可写 / 目标不存在等）。 */
export class TeamWriteError extends Error {
  readonly code: 'team_id_invalid' | 'team_write_failed' | 'team_not_found'
  readonly path?: string

  constructor(code: TeamWriteError['code'], message: string, path?: string) {
    super(`${code}: ${message}${path ? ` (${path})` : ''}`)
    this.name = 'TeamWriteError'
    this.code = code
    this.path = path
  }
}

const KEBAB_CASE_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/

export interface TeamWriteResult {
  written: string[]
  skipped: { path: string; reason: string }[]
  /** 工作流随名册收窄等诊断（供 CLI/HTTP 打印）。 */
  issues: ValidationIssue[]
}

/** 团队定义补丁（只列可改字段；`team_id` 是文件名，不支持改）。 */
export interface TeamPatch {
  name?: string
  description?: string
  members?: TeamMember[]
  skills?: string[]
  knowledge?: KnowledgeBinding
  deposit?: Partial<DepositPolicy>
  arbitration?: string[]
  reworkLimit?: number
}

export interface EditTeamInput {
  teamId: string
  teamsDir: string
  patch: TeamPatch
}

export interface RemoveTeamInput {
  teamId: string
  teamsDir: string
}

/**
 * `team edit`：对既有团队打字段补丁。目标不存在 → `team_not_found`（本命令只改，不隐式新建）。
 */
export async function editTeam(input: EditTeamInput): Promise<TeamWriteResult> {
  const teamId = input.teamId.trim()
  const path = join(input.teamsDir, `${teamId}.md`)
  if (!existsSync(path)) {
    throw new TeamWriteError('team_not_found', `团队不存在，无法修改：${teamId}`, path)
  }
  const { markdown, issues } = patchTeamRaw(readFileSync(path, 'utf8'), input.patch)
  writeFile(path, markdown)
  return { written: [path], skipped: [], issues }
}

/**
 * 纯函数：给团队 Markdown 打补丁。
 *
 * 返回 `issues` 目前只有一条来源：`members` 收窄时被剔除的角色/阶段（`workflow_pruned`），
 * 让人看得见「改名册顺手动了工作流」这件事。
 */
export function patchTeamRaw(raw: string, patch: TeamPatch): { markdown: string; issues: ValidationIssue[] } {
  const { data, body } = splitFrontmatter(raw)
  const fm: FrontmatterData = data ?? {}
  const hadMarker = raw.includes('<!-- generated by prism (team: ')
  const issues: ValidationIssue[] = []
  let nextBody = body.replace(/^\n+/, '')

  if (patch.name !== undefined) fm.name = patch.name
  if (patch.description !== undefined) fm.description = patch.description
  if (patch.skills !== undefined) fm.skills = [...patch.skills]
  if (patch.knowledge !== undefined) {
    fm.knowledge = {
      layers: [...patch.knowledge.layers],
      ...(patch.knowledge.books !== undefined ? { books: [...patch.knowledge.books] } : {}),
    }
  }
  if (patch.arbitration !== undefined) fm.arbitration = [...patch.arbitration]
  if (patch.reworkLimit !== undefined) fm.rework_limit = patch.reworkLimit
  if (patch.deposit !== undefined) fm.deposit = mergeDeposit(fm.deposit, patch.deposit)

  if (patch.members !== undefined) {
    fm.members = patch.members.map((m) => ({ role: m.role, count: m.count }))
    // 名册收窄 → 工作流就地裁剪（与 `team new --members` 同一实现）
    const memberRoles = new Set(patch.members.map((m) => stripInstanceMarker(m.role)))
    const { stages, prunedRoles, prunedStages } = narrowWorkflow(parseWorkflowTable(nextBody), memberRoles)
    nextBody = replaceWorkflowSection(nextBody, renderWorkflowTable(stages))
    if (prunedRoles.length > 0 || prunedStages.length > 0) {
      issues.push({
        level: 'warning',
        code: 'workflow_pruned',
        message: `工作流已按名册收窄：剔除角色 [${[...new Set(prunedRoles)].join(', ') || '—'}]，删除阶段 [${prunedStages.join(', ') || '—'}]`,
      })
    }
  }

  const content = renderMarkdownFile(fm, normalizeBlankLines(nextBody.trimEnd()))
  const teamId = typeof fm.team_id === 'string' ? fm.team_id : ''
  const markdown = hadMarker && teamId !== '' ? `${content.trimEnd()}\n<!-- generated by prism (team: ${teamId}) -->\n` : content
  return { markdown, issues }
}

/**
 * `team rm`：删除团队文件本体（扁平 `<id>.md` + 兼容形态 `<id>/AGENTS.md`）。
 * 两处都不存在 → `team_not_found`。删除是否放行由调用方的写守卫决定，本函数不做二次确认。
 */
export async function removeTeam(input: RemoveTeamInput): Promise<{ removed: string[] }> {
  const teamId = input.teamId.trim()
  const flat = join(input.teamsDir, `${teamId}.md`)
  const dirForm = join(input.teamsDir, teamId, 'AGENTS.md')
  const removed: string[] = []
  if (existsSync(flat)) {
    rmSync(flat, { force: true })
    removed.push(flat)
  }
  if (existsSync(dirForm)) {
    rmSync(dirname(dirForm), { recursive: true, force: true })
    removed.push(dirForm)
  }
  if (removed.length === 0) {
    throw new TeamWriteError('team_not_found', `团队不存在，无法删除：${teamId}`, flat)
  }
  return { removed }
}

/** 校验团队 id 形状（CLI 建团队入口用）。 */
export function assertTeamId(teamId: string): void {
  if (!KEBAB_CASE_RE.test(teamId.trim())) {
    throw new TeamWriteError('team_id_invalid', `团队 id 必须 kebab-case（小写字母/数字/连字符）：${teamId}`)
  }
}

function writeFile(path: string, content: string): void {
  try {
    writeFileSync(path, content, 'utf8')
  } catch (err) {
    throw new TeamWriteError('team_write_failed', `目标文件不可写：${err instanceof Error ? err.message : String(err)}`, path)
  }
}

/** 合并 deposit 补丁（只认已知 5 键；未知/非法值忽略，不猜不崩）。 */
function mergeDeposit(current: unknown, patch: Partial<DepositPolicy>): FrontmatterData {
  const base: FrontmatterData =
    typeof current === 'object' && current !== null && !Array.isArray(current) ? { ...(current as FrontmatterData) } : {}
  for (const [key, value] of Object.entries(patch)) {
    if (value !== undefined) base[key] = value as FrontmatterData[string]
  }
  return base
}

function normalizeBlankLines(text: string): string {
  return `${text.replace(/\n{3,}/g, '\n\n').replace(/[ \t]+\n/g, '\n').trimEnd()}\n`
}
