/**
 * ZCode 适配器（HarnessAdapter 实现，harness-adapters §4）。
 *
 * - 约定字段按 harness §4.1 写死；目录全部由根目录**参数**推导，默认值
 *   仅供 detect() 只读探测，任何写操作的目标目录仍由调用方显式传入（install/activate）；
 * - renderRole = renderZcodeRole 的薄包装（design-v3 §2 P7）；parseRole = parseRoleMarkdown；
 * - Prism 扩展一律放正文，frontmatter 只含 ZCode 白名单字段。
 */

import { existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

import type { HarnessAdapter, HarnessPresence, HarnessRenderOptions, RenderedFile } from '@prism/core'

import { parseRoleMarkdown } from '../role/parse.js'
import { renderZcodeRole } from '../role/render.js'
import { renderZcodeTeam } from '../team/render.js'
import type { RoleDefinition, TeamDefinition } from '../types.js'

export const ZCODE_ADAPTER_ID = 'zcode'

/** ZCode frontmatter 字段白名单（Prism 不得越界，扩展一律放正文）。 */
export const ZCODE_FRONTMATTER_FIELDS = [
  'name', 'description', 'color', 'model', 'thoughtLevel', 'injectAgentsMd',
] as const

export interface ZcodeAdapterOptions {
  /**
   * harness 根目录（如 ~/.zcode；`~` 由 CLI 层展开后传入，Windows 下不得传字面 ~）。
   * `zcodeDir` 为兼容旧调用保留的别名。
   */
  root?: string
  /** @deprecated 用 `root`。 */
  zcodeDir?: string
  /** 项目根（renderTeamInstructions 注入 `<repo>/AGENTS.md` 用；缺省 → 该方法返回 null）。 */
  repoDir?: string
}

/** 默认 ZCode 根（仅作探测与展示缺省；写操作一律走显式参数）。 */
export const DEFAULT_ZCODE_DIR = join(homedir(), '.zcode')

/** 创建 ZCode 适配器。 */
export function createZcodeAdapter(opts: ZcodeAdapterOptions = {}): HarnessAdapter<RoleDefinition, TeamDefinition> {
  // ZCODE_DIR 是 **ZCode 专属**旧变量；在此（而非通用路径里）生效，
  // 避免它泄漏到其它 harness（插件实测：会把插件的 defaultRoot 覆盖成 ~/.zcode）。
  const root = opts.root ?? opts.zcodeDir ?? process.env['ZCODE_DIR'] ?? DEFAULT_ZCODE_DIR
  const agentsDir = join(root, 'agents')
  // 团队定义落在宿主根的 teams/（agents 的同级）——ZCode 递归扫描 agents/ 下全部 .md，
  // 团队文件含 name+description 会被误注册成 agent（R3 实测 / B7），故必须移出 agents/。
  const teamDir = join(root, 'teams')
  const adapter: HarnessAdapter<RoleDefinition, TeamDefinition> = {
    id: ZCODE_ADAPTER_ID,
    displayName: 'ZCode',
    defaultRoot: root,

    async detect(): Promise<HarnessPresence> {
      if (!existsSync(root)) {
        return { installed: false, reason: `ZCode 配置目录不存在：${root}` }
      }
      return { installed: true, configDir: root }
    },

    agent: {
      globalDir: agentsDir,
      projectDir: opts.repoDir ? join(opts.repoDir, '.zcode', 'agents') : '<repo>/.zcode/agents',
      filePattern: '<role>.md',
      teamDir,
      frontmatterFields: ZCODE_FRONTMATTER_FIELDS,
      bodyConvention: '## 核心契约',
      activation: 'session-start',
      nameMustMatchFile: true,
    },

    dispatch: {
      mechanism: 'subagent_type 名称派发',
      fallback: 'general-purpose + 契约粘入 prompt',
    },

    model: {
      declarable: true,
      overridePath: join(root, 'v2', 'agents-state.json'),
      format: 'vendor-id',
      capabilitySource: 'host-config',
    },

    skill: {
      nativeDir: join(root, 'skills'),
      ecosystemDir: join(homedir(), '.agents', 'skills'),
      format: 'SKILL.md',
      supported: true,
    },

    instructions: {
      file: 'AGENTS.md',
      projectFile: opts.repoDir ? join(opts.repoDir, 'AGENTS.md') : '<repo>/AGENTS.md',
    },

    renderRole(role: RoleDefinition, options?: HarnessRenderOptions): RenderedFile {
      const marker = `<!-- generated by prism (role: ${role.name}) -->`
      return {
        path: join(agentsDir, `${role.name}.md`),
        content: renderZcodeRole(role, options ?? {}),
        format: 'markdown',
        writePolicy: 'overwrite', // 冲突细化（marker/人写）由 install.ts 落地
        marker,
      }
    },

    /** 团队定义文件（装配产物 `<teamDir>/<team_id>.md`）。 */
    renderTeamDefinition(team: TeamDefinition): RenderedFile {
      return {
        path: join(teamDir, `${team.team_id}.md`),
        content: renderZcodeTeam(team),
        format: 'markdown',
        writePolicy: 'overwrite',
        marker: '<!-- generated by prism (team:',
      }
    },

    parseRole(content: string, filename: string): RoleDefinition {
      return parseRoleMarkdown(content, { sourcePath: filename })
    },

    renderTeamInstructions(team: TeamDefinition): RenderedFile | null {
      if (opts.repoDir === undefined) return null
      const start = `<!-- prism:team:${team.team_id}:start -->`
      const end = `<!-- prism:team:${team.team_id}:end -->`
      const workflowLines = team.workflow
        .map((s) => `| ${s.order} | ${s.stage} | ${s.roles.join(' + ')} | ${s.mode} | ${s.input} | ${s.output} | ${s.done} | ${s.reflow} |`)
        .join('\n')
      const content = [
        start,
        `# 团队约定：${team.name}（${team.team_id}）`,
        '',
        team.description,
        '',
        '## 工作流',
        '',
        '| # | 阶段 | 负责角色 | 串/并行 | 输入 | 输出 | 完成判定 | 回流路径 |',
        '| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |',
        workflowLines,
        '',
        `仲裁链：${team.arbitration.join(' > ') || '（未定义）'}`,
        `返工上限：${team.rework_limit} 轮`,
        end,
        '',
      ].join('\n')
      return {
        path: join(opts.repoDir, 'AGENTS.md'),
        content,
        format: 'markdown',
        writePolicy: 'merge', // 标记块合并注入，不整文件覆盖
        marker: start,
      }
    },
  }
  return adapter
}
